/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panelView;

public class ManajemenObatPanel extends javax.swing.JPanel {

    public ManajemenObatPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        pencarianObatPanel = new javax.swing.JPanel();
        pencarianObatLabel = new javax.swing.JLabel();
        pencarianObatTextField = new javax.swing.JTextField();
        pencarianObatButton = new javax.swing.JButton();
        formInputDataObatPanel = new javax.swing.JPanel();
        inputDataObatLabel = new javax.swing.JLabel();
        pilihBentukSediaanPanel = new javax.swing.JPanel();
        pilihBentukSediaanLabel = new javax.swing.JLabel();
        pilihBentukSediaanDropDown = new javax.swing.JComboBox<>();
        inputNamaObatPanel = new javax.swing.JPanel();
        inputNamaObatLabel = new javax.swing.JLabel();
        inputNamaObatTextField = new javax.swing.JTextField();
        simpanObatButton = new javax.swing.JButton();
        batalObatButton = new javax.swing.JButton();
        inputIdObatPanel = new javax.swing.JPanel();
        inputIdObatLabel = new javax.swing.JLabel();
        inputIdObatTextField = new javax.swing.JTextField();
        inputDosisPanel = new javax.swing.JPanel();
        inputDosisLabel = new javax.swing.JLabel();
        inputDosisTextField = new javax.swing.JTextField();
        pilihKategoriObatPanel = new javax.swing.JPanel();
        pilihKategoriObatLabel = new javax.swing.JLabel();
        obatHerbalRadioButton = new javax.swing.JRadioButton();
        obatPatenRadioButton = new javax.swing.JRadioButton();
        inputHargaSatuanPanel = new javax.swing.JPanel();
        inputHargaSatuanLabel = new javax.swing.JLabel();
        inputHargaSatuanTextField = new javax.swing.JTextField();
        inputStokObatPanel = new javax.swing.JPanel();
        inputStokObatLabel = new javax.swing.JLabel();
        inputStokObatTextField = new javax.swing.JTextField();
        obatScrollPane = new javax.swing.JScrollPane();
        obatTable = new javax.swing.JTable();
        obatButtonPanel = new javax.swing.JPanel();
        tambahObatButton = new javax.swing.JButton();
        barukanObatButton = new javax.swing.JButton();
        hapusObatButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(238, 239, 253));
        setPreferredSize(new java.awt.Dimension(1224, 811));

        mainPanel.setBackground(new java.awt.Color(238, 239, 253));

        pencarianObatPanel.setBackground(new java.awt.Color(255, 255, 255));
        pencarianObatPanel.setPreferredSize(new java.awt.Dimension(800, 70));

        pencarianObatLabel.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        pencarianObatLabel.setText("Pencarian Obat");

        pencarianObatButton.setBackground(new java.awt.Color(51, 0, 153));
        pencarianObatButton.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 12)); // NOI18N
        pencarianObatButton.setForeground(new java.awt.Color(255, 255, 255));
        pencarianObatButton.setText("Cari");

        javax.swing.GroupLayout pencarianObatPanelLayout = new javax.swing.GroupLayout(pencarianObatPanel);
        pencarianObatPanel.setLayout(pencarianObatPanelLayout);
        pencarianObatPanelLayout.setHorizontalGroup(
            pencarianObatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pencarianObatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pencarianObatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pencarianObatPanelLayout.createSequentialGroup()
                        .addComponent(pencarianObatLabel)
                        .addGap(0, 997, Short.MAX_VALUE))
                    .addGroup(pencarianObatPanelLayout.createSequentialGroup()
                        .addComponent(pencarianObatTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pencarianObatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pencarianObatPanelLayout.setVerticalGroup(
            pencarianObatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pencarianObatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pencarianObatLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pencarianObatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pencarianObatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pencarianObatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        formInputDataObatPanel.setBackground(new java.awt.Color(255, 255, 255));

        inputDataObatLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        inputDataObatLabel.setText("Data Obat");

        pilihBentukSediaanPanel.setBackground(new java.awt.Color(255, 255, 255));

        pilihBentukSediaanLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        pilihBentukSediaanLabel.setText("Bentuk sediaan");

        pilihBentukSediaanDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pilihBentukSediaanPanelLayout = new javax.swing.GroupLayout(pilihBentukSediaanPanel);
        pilihBentukSediaanPanel.setLayout(pilihBentukSediaanPanelLayout);
        pilihBentukSediaanPanelLayout.setHorizontalGroup(
            pilihBentukSediaanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pilihBentukSediaanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pilihBentukSediaanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pilihBentukSediaanPanelLayout.createSequentialGroup()
                        .addComponent(pilihBentukSediaanLabel)
                        .addGap(0, 111, Short.MAX_VALUE))
                    .addComponent(pilihBentukSediaanDropDown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pilihBentukSediaanPanelLayout.setVerticalGroup(
            pilihBentukSediaanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pilihBentukSediaanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pilihBentukSediaanLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pilihBentukSediaanDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        inputNamaObatPanel.setBackground(new java.awt.Color(255, 255, 255));

        inputNamaObatLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        inputNamaObatLabel.setText("Nama Obat");

        javax.swing.GroupLayout inputNamaObatPanelLayout = new javax.swing.GroupLayout(inputNamaObatPanel);
        inputNamaObatPanel.setLayout(inputNamaObatPanelLayout);
        inputNamaObatPanelLayout.setHorizontalGroup(
            inputNamaObatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputNamaObatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputNamaObatLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(inputNamaObatPanelLayout.createSequentialGroup()
                .addComponent(inputNamaObatTextField)
                .addContainerGap())
        );
        inputNamaObatPanelLayout.setVerticalGroup(
            inputNamaObatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputNamaObatPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inputNamaObatLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputNamaObatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        simpanObatButton.setBackground(new java.awt.Color(51, 178, 73));
        simpanObatButton.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 12)); // NOI18N
        simpanObatButton.setForeground(new java.awt.Color(255, 255, 255));
        simpanObatButton.setText("Simpan");

        batalObatButton.setBackground(new java.awt.Color(237, 8, 0));
        batalObatButton.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 12)); // NOI18N
        batalObatButton.setForeground(new java.awt.Color(255, 255, 255));
        batalObatButton.setText("Batal");
        batalObatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalObatButtonActionPerformed(evt);
            }
        });

        inputIdObatPanel.setBackground(new java.awt.Color(255, 255, 255));

        inputIdObatLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        inputIdObatLabel.setText("ID-Obat");

        javax.swing.GroupLayout inputIdObatPanelLayout = new javax.swing.GroupLayout(inputIdObatPanel);
        inputIdObatPanel.setLayout(inputIdObatPanelLayout);
        inputIdObatPanelLayout.setHorizontalGroup(
            inputIdObatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputIdObatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputIdObatLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(inputIdObatPanelLayout.createSequentialGroup()
                .addComponent(inputIdObatTextField)
                .addContainerGap())
        );
        inputIdObatPanelLayout.setVerticalGroup(
            inputIdObatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputIdObatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputIdObatLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inputIdObatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        inputDosisPanel.setBackground(new java.awt.Color(255, 255, 255));

        inputDosisLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        inputDosisLabel.setText("Dosis");

        inputDosisTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDosisTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputDosisPanelLayout = new javax.swing.GroupLayout(inputDosisPanel);
        inputDosisPanel.setLayout(inputDosisPanelLayout);
        inputDosisPanelLayout.setHorizontalGroup(
            inputDosisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputDosisPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputDosisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputDosisTextField)
                    .addGroup(inputDosisPanelLayout.createSequentialGroup()
                        .addComponent(inputDosisLabel)
                        .addGap(0, 174, Short.MAX_VALUE)))
                .addContainerGap())
        );
        inputDosisPanelLayout.setVerticalGroup(
            inputDosisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputDosisPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputDosisLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputDosisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pilihKategoriObatPanel.setBackground(new java.awt.Color(255, 255, 255));

        pilihKategoriObatLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        pilihKategoriObatLabel.setText("Kategori");

        obatHerbalRadioButton.setText("Obat Herbal");

        obatPatenRadioButton.setText("Obat Paten");

        javax.swing.GroupLayout pilihKategoriObatPanelLayout = new javax.swing.GroupLayout(pilihKategoriObatPanel);
        pilihKategoriObatPanel.setLayout(pilihKategoriObatPanelLayout);
        pilihKategoriObatPanelLayout.setHorizontalGroup(
            pilihKategoriObatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pilihKategoriObatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pilihKategoriObatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pilihKategoriObatLabel)
                    .addGroup(pilihKategoriObatPanelLayout.createSequentialGroup()
                        .addComponent(obatHerbalRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(obatPatenRadioButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pilihKategoriObatPanelLayout.setVerticalGroup(
            pilihKategoriObatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pilihKategoriObatPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pilihKategoriObatLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pilihKategoriObatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(obatHerbalRadioButton)
                    .addComponent(obatPatenRadioButton))
                .addGap(8, 8, 8))
        );

        inputHargaSatuanPanel.setBackground(new java.awt.Color(255, 255, 255));

        inputHargaSatuanLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        inputHargaSatuanLabel.setText("Harga Satuan");

        inputHargaSatuanTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputHargaSatuanTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputHargaSatuanPanelLayout = new javax.swing.GroupLayout(inputHargaSatuanPanel);
        inputHargaSatuanPanel.setLayout(inputHargaSatuanPanelLayout);
        inputHargaSatuanPanelLayout.setHorizontalGroup(
            inputHargaSatuanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputHargaSatuanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputHargaSatuanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputHargaSatuanTextField)
                    .addGroup(inputHargaSatuanPanelLayout.createSequentialGroup()
                        .addComponent(inputHargaSatuanLabel)
                        .addGap(0, 114, Short.MAX_VALUE)))
                .addContainerGap())
        );
        inputHargaSatuanPanelLayout.setVerticalGroup(
            inputHargaSatuanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputHargaSatuanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputHargaSatuanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputHargaSatuanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        inputStokObatPanel.setBackground(new java.awt.Color(255, 255, 255));

        inputStokObatLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        inputStokObatLabel.setText("Stok Obat");

        inputStokObatTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputStokObatTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputStokObatPanelLayout = new javax.swing.GroupLayout(inputStokObatPanel);
        inputStokObatPanel.setLayout(inputStokObatPanelLayout);
        inputStokObatPanelLayout.setHorizontalGroup(
            inputStokObatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputStokObatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputStokObatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputStokObatTextField)
                    .addGroup(inputStokObatPanelLayout.createSequentialGroup()
                        .addComponent(inputStokObatLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        inputStokObatPanelLayout.setVerticalGroup(
            inputStokObatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputStokObatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputStokObatLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputStokObatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout formInputDataObatPanelLayout = new javax.swing.GroupLayout(formInputDataObatPanel);
        formInputDataObatPanel.setLayout(formInputDataObatPanelLayout);
        formInputDataObatPanelLayout.setHorizontalGroup(
            formInputDataObatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formInputDataObatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formInputDataObatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formInputDataObatPanelLayout.createSequentialGroup()
                        .addGroup(formInputDataObatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(inputIdObatPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputNamaObatPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputDataObatLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, formInputDataObatPanelLayout.createSequentialGroup()
                                .addComponent(pilihBentukSediaanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputDosisPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pilihKategoriObatPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(formInputDataObatPanelLayout.createSequentialGroup()
                        .addGroup(formInputDataObatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(simpanObatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputHargaSatuanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(formInputDataObatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputStokObatPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(batalObatButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        formInputDataObatPanelLayout.setVerticalGroup(
            formInputDataObatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formInputDataObatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputDataObatLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputIdObatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputNamaObatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formInputDataObatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputDosisPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pilihBentukSediaanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pilihKategoriObatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formInputDataObatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputStokObatPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputHargaSatuanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formInputDataObatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanObatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(batalObatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(227, Short.MAX_VALUE))
        );

        obatTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        obatScrollPane.setViewportView(obatTable);

        obatButtonPanel.setBackground(new java.awt.Color(255, 255, 255));

        tambahObatButton.setBackground(new java.awt.Color(51, 178, 73));
        tambahObatButton.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 12)); // NOI18N
        tambahObatButton.setForeground(new java.awt.Color(255, 255, 255));
        tambahObatButton.setText("Tambah");
        tambahObatButton.setPreferredSize(new java.awt.Dimension(124, 24));

        barukanObatButton.setBackground(new java.awt.Color(255, 189, 3));
        barukanObatButton.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 12)); // NOI18N
        barukanObatButton.setForeground(new java.awt.Color(255, 255, 255));
        barukanObatButton.setText("Barukan");

        hapusObatButton.setBackground(new java.awt.Color(237, 8, 0));
        hapusObatButton.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 12)); // NOI18N
        hapusObatButton.setForeground(new java.awt.Color(255, 255, 255));
        hapusObatButton.setText("Hapus");

        javax.swing.GroupLayout obatButtonPanelLayout = new javax.swing.GroupLayout(obatButtonPanel);
        obatButtonPanel.setLayout(obatButtonPanelLayout);
        obatButtonPanelLayout.setHorizontalGroup(
            obatButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(obatButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambahObatButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(barukanObatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(hapusObatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        obatButtonPanelLayout.setVerticalGroup(
            obatButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(obatButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(obatButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tambahObatButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(obatButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(barukanObatButton, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                        .addComponent(hapusObatButton, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pencarianObatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(formInputDataObatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(obatButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(obatScrollPane)))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(pencarianObatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(obatScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(obatButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formInputDataObatPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void batalObatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalObatButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_batalObatButtonActionPerformed

    private void inputDosisTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDosisTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDosisTextFieldActionPerformed

    private void inputHargaSatuanTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputHargaSatuanTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputHargaSatuanTextFieldActionPerformed

    private void inputStokObatTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputStokObatTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputStokObatTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barukanObatButton;
    private javax.swing.JButton batalObatButton;
    private javax.swing.JPanel formInputDataObatPanel;
    private javax.swing.JButton hapusObatButton;
    private javax.swing.JLabel inputDataObatLabel;
    private javax.swing.JLabel inputDosisLabel;
    private javax.swing.JPanel inputDosisPanel;
    private javax.swing.JTextField inputDosisTextField;
    private javax.swing.JLabel inputHargaSatuanLabel;
    private javax.swing.JPanel inputHargaSatuanPanel;
    private javax.swing.JTextField inputHargaSatuanTextField;
    private javax.swing.JLabel inputIdObatLabel;
    private javax.swing.JPanel inputIdObatPanel;
    private javax.swing.JTextField inputIdObatTextField;
    private javax.swing.JLabel inputNamaObatLabel;
    private javax.swing.JPanel inputNamaObatPanel;
    private javax.swing.JTextField inputNamaObatTextField;
    private javax.swing.JLabel inputStokObatLabel;
    private javax.swing.JPanel inputStokObatPanel;
    private javax.swing.JTextField inputStokObatTextField;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel obatButtonPanel;
    private javax.swing.JRadioButton obatHerbalRadioButton;
    private javax.swing.JRadioButton obatPatenRadioButton;
    private javax.swing.JScrollPane obatScrollPane;
    private javax.swing.JTable obatTable;
    private javax.swing.JButton pencarianObatButton;
    private javax.swing.JLabel pencarianObatLabel;
    private javax.swing.JPanel pencarianObatPanel;
    private javax.swing.JTextField pencarianObatTextField;
    private javax.swing.JComboBox<String> pilihBentukSediaanDropDown;
    private javax.swing.JLabel pilihBentukSediaanLabel;
    private javax.swing.JPanel pilihBentukSediaanPanel;
    private javax.swing.JLabel pilihKategoriObatLabel;
    private javax.swing.JPanel pilihKategoriObatPanel;
    private javax.swing.JButton simpanObatButton;
    private javax.swing.JButton tambahObatButton;
    // End of variables declaration//GEN-END:variables
}
