/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panelView;
import control.PoliklinikControl;
import model.Poliklinik;
import exception.InputKosongException;


public class ManajemenPoliKlinikPanel extends javax.swing.JPanel {
    private PoliklinikControl poliControl = new PoliklinikControl();
    private String action = null;
    private String selectedId = null;

    public ManajemenPoliKlinikPanel() {
        initComponents();
        setOpaque(false);
        showPoliKlinik();
        setComponentsPoli(false);
        setEditDeleteButtonPoli(false);
        clearTextPoli();
    }
    
    public void setComponentsPoli(boolean value) {
        inputIdPoliKlinikTextField.setEnabled(value);
        inputNamaPoliKlinikTextField.setEnabled(value);
        inputLokasiRuanganTextField.setEnabled(value);
        inputJamOperasionalTextField.setEnabled(value);
        simpanPoliKlinikButton.setEnabled(value);
        batalPoliKlinikButton.setEnabled(value);
    }

    public void setEditDeleteButtonPoli(boolean value) {
        barukanPoliKlinikButton.setEnabled(value);
        hapusPoliKlinikButton.setEnabled(value);
    }
    
    public void clearTextPoli() {
        inputIdPoliKlinikTextField.setText("");
        inputNamaPoliKlinikTextField.setText("");
        inputLokasiRuanganTextField.setText("");
        inputJamOperasionalTextField.setText("");
        pencarianPoliKlinikTextField.setText("");
    }

    public void showPoliKlinik() {
        PoliKlinikTable.setModel(poliControl.showTable(""));
    }

    public void doSearchPoli() {
        if(pencarianPoliKlinikTextField.getText().isEmpty()){
            showPoliKlinik();
            return;
        }
        PoliKlinikTable.setModel(poliControl.showTable(pencarianPoliKlinikTextField.getText()));
        setComponentsPoli(false);
        setEditDeleteButtonPoli(false);
        clearTextPoli();
        tambahPoliKlinikButton.setEnabled(true);
    }

    public void inputKosongException() throws Exception {
        if(inputIdPoliKlinikTextField.getText().isEmpty() ||
           inputNamaPoliKlinikTextField.getText().isEmpty() ||
           inputLokasiRuanganTextField.getText().isEmpty() ||
           inputJamOperasionalTextField.getText().isEmpty()) {
            throw new Exception("Seluruh Data Input Tidak Boleh Kosong!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        pencarianPoliKlinikPanel = new javax.swing.JPanel();
        pencarianPoliKlinikLabel = new javax.swing.JLabel();
        pencarianPoliKlinikTextField = new javax.swing.JTextField();
        pencarianPoliKlinikButton = new javax.swing.JButton();
        formInputDataPoliKlinikPanel = new javax.swing.JPanel();
        inputDataPoliKlinikLabel = new javax.swing.JLabel();
        inputIdPoliKlinikPanel = new javax.swing.JPanel();
        inputIdPoliKlinikLabel = new javax.swing.JLabel();
        inputIdPoliKlinikTextField = new javax.swing.JTextField();
        simpanPoliKlinikButton = new javax.swing.JButton();
        batalPoliKlinikButton = new javax.swing.JButton();
        inputJamOperasionalPanel = new javax.swing.JPanel();
        inputJamOperasionalLabel = new javax.swing.JLabel();
        inputJamOperasionalTextField = new javax.swing.JTextField();
        inputLokasiRuanganPanel = new javax.swing.JPanel();
        inputLokasiRuanganLabel = new javax.swing.JLabel();
        inputLokasiRuanganTextField = new javax.swing.JTextField();
        inputNamaPoliKlinikPanel = new javax.swing.JPanel();
        inputNamaPoliKlinikLabel = new javax.swing.JLabel();
        inputNamaPoliKlinikTextField = new javax.swing.JTextField();
        PoliKlinikScrollPane = new javax.swing.JScrollPane();
        PoliKlinikTable = new javax.swing.JTable();
        poliKlinikButtonPanel = new javax.swing.JPanel();
        tambahPoliKlinikButton = new javax.swing.JButton();
        barukanPoliKlinikButton = new javax.swing.JButton();
        hapusPoliKlinikButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(238, 239, 253));
        setPreferredSize(new java.awt.Dimension(1224, 811));

        mainPanel.setBackground(new java.awt.Color(238, 239, 253));

        pencarianPoliKlinikPanel.setBackground(new java.awt.Color(255, 255, 255));
        pencarianPoliKlinikPanel.setPreferredSize(new java.awt.Dimension(800, 70));

        pencarianPoliKlinikLabel.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        pencarianPoliKlinikLabel.setText("Pencarian Poli Klinik");

        pencarianPoliKlinikTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pencarianPoliKlinikTextFieldKeyPressed(evt);
            }
        });

        pencarianPoliKlinikButton.setBackground(new java.awt.Color(51, 0, 153));
        pencarianPoliKlinikButton.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 12)); // NOI18N
        pencarianPoliKlinikButton.setForeground(new java.awt.Color(255, 255, 255));
        pencarianPoliKlinikButton.setText("Cari");
        pencarianPoliKlinikButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pencarianPoliKlinikButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pencarianPoliKlinikPanelLayout = new javax.swing.GroupLayout(pencarianPoliKlinikPanel);
        pencarianPoliKlinikPanel.setLayout(pencarianPoliKlinikPanelLayout);
        pencarianPoliKlinikPanelLayout.setHorizontalGroup(
            pencarianPoliKlinikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pencarianPoliKlinikPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pencarianPoliKlinikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pencarianPoliKlinikPanelLayout.createSequentialGroup()
                        .addComponent(pencarianPoliKlinikLabel)
                        .addGap(0, 955, Short.MAX_VALUE))
                    .addGroup(pencarianPoliKlinikPanelLayout.createSequentialGroup()
                        .addComponent(pencarianPoliKlinikTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pencarianPoliKlinikButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pencarianPoliKlinikPanelLayout.setVerticalGroup(
            pencarianPoliKlinikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pencarianPoliKlinikPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pencarianPoliKlinikLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pencarianPoliKlinikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pencarianPoliKlinikTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pencarianPoliKlinikButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        formInputDataPoliKlinikPanel.setBackground(new java.awt.Color(255, 255, 255));

        inputDataPoliKlinikLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        inputDataPoliKlinikLabel.setText("Data Poli Klinik");

        inputIdPoliKlinikPanel.setBackground(new java.awt.Color(255, 255, 255));

        inputIdPoliKlinikLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        inputIdPoliKlinikLabel.setText("ID PoliKlinik");

        javax.swing.GroupLayout inputIdPoliKlinikPanelLayout = new javax.swing.GroupLayout(inputIdPoliKlinikPanel);
        inputIdPoliKlinikPanel.setLayout(inputIdPoliKlinikPanelLayout);
        inputIdPoliKlinikPanelLayout.setHorizontalGroup(
            inputIdPoliKlinikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputIdPoliKlinikPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputIdPoliKlinikLabel)
                .addContainerGap(342, Short.MAX_VALUE))
            .addGroup(inputIdPoliKlinikPanelLayout.createSequentialGroup()
                .addComponent(inputIdPoliKlinikTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        inputIdPoliKlinikPanelLayout.setVerticalGroup(
            inputIdPoliKlinikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputIdPoliKlinikPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputIdPoliKlinikLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inputIdPoliKlinikTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
        );

        simpanPoliKlinikButton.setBackground(new java.awt.Color(51, 178, 73));
        simpanPoliKlinikButton.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 12)); // NOI18N
        simpanPoliKlinikButton.setForeground(new java.awt.Color(255, 255, 255));
        simpanPoliKlinikButton.setText("Simpan");
        simpanPoliKlinikButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanPoliKlinikButtonActionPerformed(evt);
            }
        });

        batalPoliKlinikButton.setBackground(new java.awt.Color(237, 8, 0));
        batalPoliKlinikButton.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 12)); // NOI18N
        batalPoliKlinikButton.setForeground(new java.awt.Color(255, 255, 255));
        batalPoliKlinikButton.setText("Batal");
        batalPoliKlinikButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalPoliKlinikButtonActionPerformed(evt);
            }
        });

        inputJamOperasionalPanel.setBackground(new java.awt.Color(255, 255, 255));

        inputJamOperasionalLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        inputJamOperasionalLabel.setText("Jam Operasional");

        javax.swing.GroupLayout inputJamOperasionalPanelLayout = new javax.swing.GroupLayout(inputJamOperasionalPanel);
        inputJamOperasionalPanel.setLayout(inputJamOperasionalPanelLayout);
        inputJamOperasionalPanelLayout.setHorizontalGroup(
            inputJamOperasionalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputJamOperasionalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputJamOperasionalLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(inputJamOperasionalPanelLayout.createSequentialGroup()
                .addComponent(inputJamOperasionalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        inputJamOperasionalPanelLayout.setVerticalGroup(
            inputJamOperasionalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputJamOperasionalPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inputJamOperasionalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputJamOperasionalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        inputLokasiRuanganPanel.setBackground(new java.awt.Color(255, 255, 255));

        inputLokasiRuanganLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        inputLokasiRuanganLabel.setText("Lokasi Ruangan");

        javax.swing.GroupLayout inputLokasiRuanganPanelLayout = new javax.swing.GroupLayout(inputLokasiRuanganPanel);
        inputLokasiRuanganPanel.setLayout(inputLokasiRuanganPanelLayout);
        inputLokasiRuanganPanelLayout.setHorizontalGroup(
            inputLokasiRuanganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputLokasiRuanganPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputLokasiRuanganLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(inputLokasiRuanganPanelLayout.createSequentialGroup()
                .addComponent(inputLokasiRuanganTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        inputLokasiRuanganPanelLayout.setVerticalGroup(
            inputLokasiRuanganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputLokasiRuanganPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inputLokasiRuanganLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputLokasiRuanganTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        inputNamaPoliKlinikPanel.setBackground(new java.awt.Color(255, 255, 255));

        inputNamaPoliKlinikLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        inputNamaPoliKlinikLabel.setText("Nama PoliKlinik");

        javax.swing.GroupLayout inputNamaPoliKlinikPanelLayout = new javax.swing.GroupLayout(inputNamaPoliKlinikPanel);
        inputNamaPoliKlinikPanel.setLayout(inputNamaPoliKlinikPanelLayout);
        inputNamaPoliKlinikPanelLayout.setHorizontalGroup(
            inputNamaPoliKlinikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputNamaPoliKlinikPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputNamaPoliKlinikLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(inputNamaPoliKlinikPanelLayout.createSequentialGroup()
                .addComponent(inputNamaPoliKlinikTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        inputNamaPoliKlinikPanelLayout.setVerticalGroup(
            inputNamaPoliKlinikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputNamaPoliKlinikPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inputNamaPoliKlinikLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputNamaPoliKlinikTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout formInputDataPoliKlinikPanelLayout = new javax.swing.GroupLayout(formInputDataPoliKlinikPanel);
        formInputDataPoliKlinikPanel.setLayout(formInputDataPoliKlinikPanelLayout);
        formInputDataPoliKlinikPanelLayout.setHorizontalGroup(
            formInputDataPoliKlinikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formInputDataPoliKlinikPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formInputDataPoliKlinikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputIdPoliKlinikPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(formInputDataPoliKlinikPanelLayout.createSequentialGroup()
                        .addGroup(formInputDataPoliKlinikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inputDataPoliKlinikLabel)
                            .addComponent(inputJamOperasionalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(formInputDataPoliKlinikPanelLayout.createSequentialGroup()
                                .addComponent(simpanPoliKlinikButton, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(batalPoliKlinikButton, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(inputLokasiRuanganPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputNamaPoliKlinikPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        formInputDataPoliKlinikPanelLayout.setVerticalGroup(
            formInputDataPoliKlinikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formInputDataPoliKlinikPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputDataPoliKlinikLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputIdPoliKlinikPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputLokasiRuanganPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(inputNamaPoliKlinikPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputJamOperasionalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formInputDataPoliKlinikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanPoliKlinikButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(batalPoliKlinikButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PoliKlinikTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        PoliKlinikTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PoliKlinikTableMouseClicked(evt);
            }
        });
        PoliKlinikScrollPane.setViewportView(PoliKlinikTable);

        poliKlinikButtonPanel.setBackground(new java.awt.Color(255, 255, 255));

        tambahPoliKlinikButton.setBackground(new java.awt.Color(51, 178, 73));
        tambahPoliKlinikButton.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 12)); // NOI18N
        tambahPoliKlinikButton.setForeground(new java.awt.Color(255, 255, 255));
        tambahPoliKlinikButton.setText("Tambah");
        tambahPoliKlinikButton.setPreferredSize(new java.awt.Dimension(124, 24));
        tambahPoliKlinikButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahPoliKlinikButtonActionPerformed(evt);
            }
        });

        barukanPoliKlinikButton.setBackground(new java.awt.Color(255, 189, 3));
        barukanPoliKlinikButton.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 12)); // NOI18N
        barukanPoliKlinikButton.setForeground(new java.awt.Color(255, 255, 255));
        barukanPoliKlinikButton.setText("Barukan");
        barukanPoliKlinikButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barukanPoliKlinikButtonActionPerformed(evt);
            }
        });

        hapusPoliKlinikButton.setBackground(new java.awt.Color(237, 8, 0));
        hapusPoliKlinikButton.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 12)); // NOI18N
        hapusPoliKlinikButton.setForeground(new java.awt.Color(255, 255, 255));
        hapusPoliKlinikButton.setText("Hapus");
        hapusPoliKlinikButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusPoliKlinikButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout poliKlinikButtonPanelLayout = new javax.swing.GroupLayout(poliKlinikButtonPanel);
        poliKlinikButtonPanel.setLayout(poliKlinikButtonPanelLayout);
        poliKlinikButtonPanelLayout.setHorizontalGroup(
            poliKlinikButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(poliKlinikButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambahPoliKlinikButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(barukanPoliKlinikButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hapusPoliKlinikButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        poliKlinikButtonPanelLayout.setVerticalGroup(
            poliKlinikButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(poliKlinikButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(poliKlinikButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tambahPoliKlinikButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(poliKlinikButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(barukanPoliKlinikButton, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                        .addComponent(hapusPoliKlinikButton, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pencarianPoliKlinikPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1146, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(poliKlinikButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(formInputDataPoliKlinikPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PoliKlinikScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(pencarianPoliKlinikPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PoliKlinikScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(poliKlinikButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formInputDataPoliKlinikPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void batalPoliKlinikButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalPoliKlinikButtonActionPerformed
        clearTextPoli();
        action = null;
        selectedId = null;
        setComponentsPoli(false);
        setEditDeleteButtonPoli(false);
        tambahPoliKlinikButton.setEnabled(true);
    }//GEN-LAST:event_batalPoliKlinikButtonActionPerformed

    private void tambahPoliKlinikButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahPoliKlinikButtonActionPerformed
        action = "tambah";
        clearTextPoli();
        setComponentsPoli(true);
        setEditDeleteButtonPoli(false);
    }//GEN-LAST:event_tambahPoliKlinikButtonActionPerformed

    private void barukanPoliKlinikButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barukanPoliKlinikButtonActionPerformed
        action = "ubah";
        setComponentsPoli(true);
        inputIdPoliKlinikTextField.setEnabled(false); // ID jangan diubah saat edit
        setEditDeleteButtonPoli(true);
    }//GEN-LAST:event_barukanPoliKlinikButtonActionPerformed

    private void hapusPoliKlinikButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusPoliKlinikButtonActionPerformed
        action = "hapus";
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus data Poli Klinik ini?", "Konfirmasi Hapus", javax.swing.JOptionPane.YES_NO_OPTION);
        
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            poliControl.delete(selectedId); 
            clearTextPoli();
            setComponentsPoli(false);
            setEditDeleteButtonPoli(false);
            showPoliKlinik();
            tambahPoliKlinikButton.setEnabled(true);
        }
    }//GEN-LAST:event_hapusPoliKlinikButtonActionPerformed

    private void simpanPoliKlinikButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanPoliKlinikButtonActionPerformed
        try {
            // Pengecekan input kosong
            inputKosongException();

            // Memunculkan Dialog Konfirmasi (Yes/No/Cancel)
            int confirm = javax.swing.JOptionPane.showConfirmDialog(
                this, 
                "Apakah Anda yakin ingin melakukan aksi " + action + " pada data Poli Klinik ini?", 
                "Konfirmasi Simpan", 
                javax.swing.JOptionPane.YES_NO_CANCEL_OPTION
            );
            
            if (confirm != javax.swing.JOptionPane.YES_OPTION) {
                return; 
            }

            
            model.Poliklinik poli = new model.Poliklinik(
                inputIdPoliKlinikTextField.getText(),
                inputNamaPoliKlinikTextField.getText(),
                inputLokasiRuanganTextField.getText(),
                inputJamOperasionalTextField.getText()
            );

            if(action.equals("tambah")) {
                poliControl.insert(poli);
            } else if(action.equals("ubah")) {
                poliControl.update(poli, selectedId);
            }
            clearTextPoli();
            setComponentsPoli(false);
            setEditDeleteButtonPoli(false);
            tambahPoliKlinikButton.setEnabled(true);
            showPoliKlinik();
            
            selectedId = null;
            action = null;

        } catch(Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_simpanPoliKlinikButtonActionPerformed

    private void PoliKlinikTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PoliKlinikTableMouseClicked
        int clickedRow = PoliKlinikTable.getSelectedRow();
        if(clickedRow < 0) return;

        javax.swing.table.TableModel tableModel = PoliKlinikTable.getModel();

        setComponentsPoli(false); 
        setEditDeleteButtonPoli(true);
        tambahPoliKlinikButton.setEnabled(true);

        selectedId = tableModel.getValueAt(clickedRow, 0).toString();

        inputIdPoliKlinikTextField.setText(selectedId);
        inputNamaPoliKlinikTextField.setText(tableModel.getValueAt(clickedRow, 1).toString());
        inputLokasiRuanganTextField.setText(tableModel.getValueAt(clickedRow, 2).toString());
        inputJamOperasionalTextField.setText(tableModel.getValueAt(clickedRow, 3).toString());
    }//GEN-LAST:event_PoliKlinikTableMouseClicked

    private void pencarianPoliKlinikTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pencarianPoliKlinikTextFieldKeyPressed
        if(evt.getKeyChar() == '\n'){
            doSearchPoli();
        }
    }//GEN-LAST:event_pencarianPoliKlinikTextFieldKeyPressed

    private void pencarianPoliKlinikButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pencarianPoliKlinikButtonActionPerformed
        doSearchPoli();
    }//GEN-LAST:event_pencarianPoliKlinikButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane PoliKlinikScrollPane;
    private javax.swing.JTable PoliKlinikTable;
    private javax.swing.JButton barukanPoliKlinikButton;
    private javax.swing.JButton batalPoliKlinikButton;
    private javax.swing.JPanel formInputDataPoliKlinikPanel;
    private javax.swing.JButton hapusPoliKlinikButton;
    private javax.swing.JLabel inputDataPoliKlinikLabel;
    private javax.swing.JLabel inputIdPoliKlinikLabel;
    private javax.swing.JPanel inputIdPoliKlinikPanel;
    private javax.swing.JTextField inputIdPoliKlinikTextField;
    private javax.swing.JLabel inputJamOperasionalLabel;
    private javax.swing.JPanel inputJamOperasionalPanel;
    private javax.swing.JTextField inputJamOperasionalTextField;
    private javax.swing.JLabel inputLokasiRuanganLabel;
    private javax.swing.JPanel inputLokasiRuanganPanel;
    private javax.swing.JTextField inputLokasiRuanganTextField;
    private javax.swing.JLabel inputNamaPoliKlinikLabel;
    private javax.swing.JPanel inputNamaPoliKlinikPanel;
    private javax.swing.JTextField inputNamaPoliKlinikTextField;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton pencarianPoliKlinikButton;
    private javax.swing.JLabel pencarianPoliKlinikLabel;
    private javax.swing.JPanel pencarianPoliKlinikPanel;
    private javax.swing.JTextField pencarianPoliKlinikTextField;
    private javax.swing.JPanel poliKlinikButtonPanel;
    private javax.swing.JButton simpanPoliKlinikButton;
    private javax.swing.JButton tambahPoliKlinikButton;
    // End of variables declaration//GEN-END:variables
}
