/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panelView;
import control.DokterControl;
import model.Dokter;

public class ManajemenDokterPanel extends javax.swing.JPanel {
    private DokterControl dokterControl = new DokterControl();
    private String action = null;
    private String selectedId = null;
    private boolean statusAktif = true; 

    public ManajemenDokterPanel() {
        initComponents();
        setOpaque(false);
        showDokter();
        setComponentsDokter(false);
        setEditDeleteButtonDokter(false);
        clearTextDokter();
    }
    
    public void setComponentsDokter(boolean value) {
        inputNamaDokterTextField.setEnabled(value);
        inputNomorSTRTextField.setEnabled(value);
        inputSpesialisasiDokterTextField.setEnabled(value);
        inputTarifDokterTextField.setEnabled(value);
        inputStatusDokterButton.setEnabled(value);
        simpanDokterButton.setEnabled(value);
        batalDokterButton.setEnabled(value);
    }

    public void setEditDeleteButtonDokter(boolean value) {
        barukanDokterButton.setEnabled(value);
        hapusDokterButton.setEnabled(value);
    }

    public void clearTextDokter() {
        inputNamaDokterTextField.setText("");
        inputNomorSTRTextField.setText("");
        inputSpesialisasiDokterTextField.setText("");
        inputTarifDokterTextField.setText("");
        pencarianDokterTextField.setText("");
        statusAktif = true;
        inputStatusDokterButton.setText("Aktif");
    }

    public void showDokter() {
        dokterTable.setModel(dokterControl.showTable(""));
    }

    public void doSearchDokter() {
        if(pencarianDokterTextField.getText().isEmpty()){
            showDokter();
            return;
        }
        dokterTable.setModel(dokterControl.showTable(pencarianDokterTextField.getText()));
        setComponentsDokter(false);
        setEditDeleteButtonDokter(false);
        clearTextDokter();
        tambahDokterButton.setEnabled(true);
    }

    public void inputKosongException() throws Exception {
        if(inputNamaDokterTextField.getText().isEmpty() ||
           inputNomorSTRTextField.getText().isEmpty() ||
           inputSpesialisasiDokterTextField.getText().isEmpty() ||
           inputTarifDokterTextField.getText().isEmpty()) {
            throw new Exception("Seluruh Data Input Tidak Boleh Kosong!");
        }
    }
    
    public boolean isDouble(String str) {
        try { Double.parseDouble(str); return true; } 
        catch (NumberFormatException e) { return false; }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        pencarianDokterPanel = new javax.swing.JPanel();
        pencarianDokterLabel = new javax.swing.JLabel();
        pencarianDokterTextField = new javax.swing.JTextField();
        pencarianDokterButton = new javax.swing.JButton();
        formInputDokterPanel = new javax.swing.JPanel();
        inputDokterLabel = new javax.swing.JLabel();
        inputNomorSTRPanel = new javax.swing.JPanel();
        inputNomorSTRLabel = new javax.swing.JLabel();
        inputNomorSTRTextField = new javax.swing.JTextField();
        inputStatusDokterPanel = new javax.swing.JPanel();
        inputStatusDokterLabel = new javax.swing.JLabel();
        inputStatusDokterButton = new javax.swing.JButton();
        inputSpesialisasiDokterPanel = new javax.swing.JPanel();
        inputSpesialisasiDokterLabel = new javax.swing.JLabel();
        inputSpesialisasiDokterTextField = new javax.swing.JTextField();
        inputNamaDokterPanel = new javax.swing.JPanel();
        inputNamaDokterLabel = new javax.swing.JLabel();
        inputNamaDokterTextField = new javax.swing.JTextField();
        simpanDokterButton = new javax.swing.JButton();
        batalDokterButton = new javax.swing.JButton();
        inputTarifDokterPanel = new javax.swing.JPanel();
        inputTarifDokterLabel = new javax.swing.JLabel();
        inputTarifDokterTextField = new javax.swing.JTextField();
        dokterScrollPane = new javax.swing.JScrollPane();
        dokterTable = new javax.swing.JTable();
        dokterButtonPanel = new javax.swing.JPanel();
        tambahDokterButton = new javax.swing.JButton();
        barukanDokterButton = new javax.swing.JButton();
        hapusDokterButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(238, 239, 253));
        setPreferredSize(new java.awt.Dimension(1224, 811));

        mainPanel.setBackground(new java.awt.Color(238, 239, 253));

        pencarianDokterPanel.setBackground(new java.awt.Color(255, 255, 255));
        pencarianDokterPanel.setPreferredSize(new java.awt.Dimension(800, 70));

        pencarianDokterLabel.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        pencarianDokterLabel.setText("Pencarian Dokter");

        pencarianDokterTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pencarianDokterTextFieldKeyPressed(evt);
            }
        });

        pencarianDokterButton.setBackground(new java.awt.Color(51, 0, 153));
        pencarianDokterButton.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 12)); // NOI18N
        pencarianDokterButton.setForeground(new java.awt.Color(255, 255, 255));
        pencarianDokterButton.setText("Cari");
        pencarianDokterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pencarianDokterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pencarianDokterPanelLayout = new javax.swing.GroupLayout(pencarianDokterPanel);
        pencarianDokterPanel.setLayout(pencarianDokterPanelLayout);
        pencarianDokterPanelLayout.setHorizontalGroup(
            pencarianDokterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pencarianDokterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pencarianDokterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pencarianDokterPanelLayout.createSequentialGroup()
                        .addComponent(pencarianDokterLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pencarianDokterPanelLayout.createSequentialGroup()
                        .addComponent(pencarianDokterTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pencarianDokterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pencarianDokterPanelLayout.setVerticalGroup(
            pencarianDokterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pencarianDokterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pencarianDokterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pencarianDokterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pencarianDokterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pencarianDokterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        formInputDokterPanel.setBackground(new java.awt.Color(255, 255, 255));

        inputDokterLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        inputDokterLabel.setText("Data Dokter");

        inputNomorSTRPanel.setBackground(new java.awt.Color(255, 255, 255));

        inputNomorSTRLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        inputNomorSTRLabel.setText("Nomor STR");

        javax.swing.GroupLayout inputNomorSTRPanelLayout = new javax.swing.GroupLayout(inputNomorSTRPanel);
        inputNomorSTRPanel.setLayout(inputNomorSTRPanelLayout);
        inputNomorSTRPanelLayout.setHorizontalGroup(
            inputNomorSTRPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputNomorSTRPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputNomorSTRLabel)
                .addContainerGap(135, Short.MAX_VALUE))
            .addComponent(inputNomorSTRTextField, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        inputNomorSTRPanelLayout.setVerticalGroup(
            inputNomorSTRPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputNomorSTRPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputNomorSTRLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inputNomorSTRTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        inputStatusDokterPanel.setBackground(new java.awt.Color(255, 255, 255));
        inputStatusDokterPanel.setToolTipText("");

        inputStatusDokterLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        inputStatusDokterLabel.setText("Status Aktif");

        inputStatusDokterButton.setText("Aktif");
        inputStatusDokterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputStatusDokterButtonMouseClicked(evt);
            }
        });
        inputStatusDokterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputStatusDokterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputStatusDokterPanelLayout = new javax.swing.GroupLayout(inputStatusDokterPanel);
        inputStatusDokterPanel.setLayout(inputStatusDokterPanelLayout);
        inputStatusDokterPanelLayout.setHorizontalGroup(
            inputStatusDokterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputStatusDokterPanelLayout.createSequentialGroup()
                .addComponent(inputStatusDokterLabel)
                .addContainerGap(129, Short.MAX_VALUE))
            .addComponent(inputStatusDokterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        inputStatusDokterPanelLayout.setVerticalGroup(
            inputStatusDokterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inputStatusDokterPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inputStatusDokterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputStatusDokterButton)
                .addGap(12, 12, 12))
        );

        inputSpesialisasiDokterPanel.setBackground(new java.awt.Color(255, 255, 255));

        inputSpesialisasiDokterLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        inputSpesialisasiDokterLabel.setText("Spesialisasi");

        javax.swing.GroupLayout inputSpesialisasiDokterPanelLayout = new javax.swing.GroupLayout(inputSpesialisasiDokterPanel);
        inputSpesialisasiDokterPanel.setLayout(inputSpesialisasiDokterPanelLayout);
        inputSpesialisasiDokterPanelLayout.setHorizontalGroup(
            inputSpesialisasiDokterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputSpesialisasiDokterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputSpesialisasiDokterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputSpesialisasiDokterPanelLayout.createSequentialGroup()
                        .addComponent(inputSpesialisasiDokterLabel)
                        .addContainerGap(131, Short.MAX_VALUE))
                    .addComponent(inputSpesialisasiDokterTextField)))
        );
        inputSpesialisasiDokterPanelLayout.setVerticalGroup(
            inputSpesialisasiDokterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputSpesialisasiDokterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputSpesialisasiDokterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inputSpesialisasiDokterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        inputNamaDokterPanel.setBackground(new java.awt.Color(255, 255, 255));

        inputNamaDokterLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        inputNamaDokterLabel.setText("Nama Lengkap");

        javax.swing.GroupLayout inputNamaDokterPanelLayout = new javax.swing.GroupLayout(inputNamaDokterPanel);
        inputNamaDokterPanel.setLayout(inputNamaDokterPanelLayout);
        inputNamaDokterPanelLayout.setHorizontalGroup(
            inputNamaDokterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputNamaDokterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputNamaDokterLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(inputNamaDokterPanelLayout.createSequentialGroup()
                .addComponent(inputNamaDokterTextField)
                .addContainerGap())
        );
        inputNamaDokterPanelLayout.setVerticalGroup(
            inputNamaDokterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputNamaDokterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputNamaDokterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inputNamaDokterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        simpanDokterButton.setBackground(new java.awt.Color(51, 178, 73));
        simpanDokterButton.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 12)); // NOI18N
        simpanDokterButton.setForeground(new java.awt.Color(255, 255, 255));
        simpanDokterButton.setText("Simpan");
        simpanDokterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanDokterButtonActionPerformed(evt);
            }
        });

        batalDokterButton.setBackground(new java.awt.Color(237, 8, 0));
        batalDokterButton.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 12)); // NOI18N
        batalDokterButton.setForeground(new java.awt.Color(255, 255, 255));
        batalDokterButton.setText("Batal");
        batalDokterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalDokterButtonActionPerformed(evt);
            }
        });

        inputTarifDokterPanel.setBackground(new java.awt.Color(255, 255, 255));

        inputTarifDokterLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        inputTarifDokterLabel.setText("Tarif Konsultasi");

        javax.swing.GroupLayout inputTarifDokterPanelLayout = new javax.swing.GroupLayout(inputTarifDokterPanel);
        inputTarifDokterPanel.setLayout(inputTarifDokterPanelLayout);
        inputTarifDokterPanelLayout.setHorizontalGroup(
            inputTarifDokterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputTarifDokterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputTarifDokterLabel)
                .addContainerGap(111, Short.MAX_VALUE))
            .addGroup(inputTarifDokterPanelLayout.createSequentialGroup()
                .addComponent(inputTarifDokterTextField)
                .addContainerGap())
        );
        inputTarifDokterPanelLayout.setVerticalGroup(
            inputTarifDokterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputTarifDokterPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inputTarifDokterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputTarifDokterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout formInputDokterPanelLayout = new javax.swing.GroupLayout(formInputDokterPanel);
        formInputDokterPanel.setLayout(formInputDokterPanelLayout);
        formInputDokterPanelLayout.setHorizontalGroup(
            formInputDokterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formInputDokterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formInputDokterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputNamaDokterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(formInputDokterPanelLayout.createSequentialGroup()
                        .addGroup(formInputDokterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputDokterLabel)
                            .addGroup(formInputDokterPanelLayout.createSequentialGroup()
                                .addComponent(inputNomorSTRPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputSpesialisasiDokterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(formInputDokterPanelLayout.createSequentialGroup()
                                .addComponent(inputTarifDokterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputStatusDokterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(formInputDokterPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(simpanDokterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(batalDokterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addContainerGap())
        );
        formInputDokterPanelLayout.setVerticalGroup(
            formInputDokterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formInputDokterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputDokterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputNamaDokterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formInputDokterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputNomorSTRPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputSpesialisasiDokterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formInputDokterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputTarifDokterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputStatusDokterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formInputDokterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(simpanDokterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(batalDokterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dokterScrollPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dokterScrollPaneMouseClicked(evt);
            }
        });

        dokterTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dokterTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dokterTableMouseClicked(evt);
            }
        });
        dokterScrollPane.setViewportView(dokterTable);

        dokterButtonPanel.setBackground(new java.awt.Color(255, 255, 255));

        tambahDokterButton.setBackground(new java.awt.Color(51, 178, 73));
        tambahDokterButton.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 12)); // NOI18N
        tambahDokterButton.setForeground(new java.awt.Color(255, 255, 255));
        tambahDokterButton.setText("Tambah");
        tambahDokterButton.setPreferredSize(new java.awt.Dimension(124, 24));
        tambahDokterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahDokterButtonActionPerformed(evt);
            }
        });

        barukanDokterButton.setBackground(new java.awt.Color(255, 189, 3));
        barukanDokterButton.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 12)); // NOI18N
        barukanDokterButton.setForeground(new java.awt.Color(255, 255, 255));
        barukanDokterButton.setText("Barukan");
        barukanDokterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barukanDokterButtonActionPerformed(evt);
            }
        });

        hapusDokterButton.setBackground(new java.awt.Color(237, 8, 0));
        hapusDokterButton.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 12)); // NOI18N
        hapusDokterButton.setForeground(new java.awt.Color(255, 255, 255));
        hapusDokterButton.setText("Hapus");
        hapusDokterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusDokterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dokterButtonPanelLayout = new javax.swing.GroupLayout(dokterButtonPanel);
        dokterButtonPanel.setLayout(dokterButtonPanelLayout);
        dokterButtonPanelLayout.setHorizontalGroup(
            dokterButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dokterButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambahDokterButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(barukanDokterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hapusDokterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        dokterButtonPanelLayout.setVerticalGroup(
            dokterButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dokterButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dokterButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tambahDokterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(dokterButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(barukanDokterButton, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                        .addComponent(hapusDokterButton, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pencarianDokterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1143, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(formInputDokterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dokterButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dokterScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(pencarianDokterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dokterScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(dokterButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formInputDokterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void batalDokterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalDokterButtonActionPerformed
        clearTextDokter();
        action = null;
        selectedId = null;
        setComponentsDokter(false);
        setEditDeleteButtonDokter(false);
        tambahDokterButton.setEnabled(true);
    }//GEN-LAST:event_batalDokterButtonActionPerformed

    private void inputStatusDokterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputStatusDokterButtonMouseClicked
        
    }//GEN-LAST:event_inputStatusDokterButtonMouseClicked

    private void inputStatusDokterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputStatusDokterButtonActionPerformed
        statusAktif = !statusAktif; 
        inputStatusDokterButton.setText(statusAktif ? "Aktif" : "Tidak Aktif");
    }//GEN-LAST:event_inputStatusDokterButtonActionPerformed

    private void tambahDokterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahDokterButtonActionPerformed
        action = "tambah";
        clearTextDokter();
        setComponentsDokter(true);
        setEditDeleteButtonDokter(false);
    }//GEN-LAST:event_tambahDokterButtonActionPerformed

    private void barukanDokterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barukanDokterButtonActionPerformed
        action = "ubah";
        setComponentsDokter(true);
        setEditDeleteButtonDokter(true);
    }//GEN-LAST:event_barukanDokterButtonActionPerformed

    private void hapusDokterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusDokterButtonActionPerformed
        action = "hapus";
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus data Dokter ini?", "Konfirmasi Hapus", javax.swing.JOptionPane.YES_NO_OPTION);
        
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            dokterControl.delete(selectedId); 
            clearTextDokter();
            setComponentsDokter(false);
            setEditDeleteButtonDokter(false);
            showDokter();
            tambahDokterButton.setEnabled(true);
        }
    }//GEN-LAST:event_hapusDokterButtonActionPerformed

    private void simpanDokterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanDokterButtonActionPerformed
        try {
            inputKosongException();
            
            if(!isDouble(inputTarifDokterTextField.getText())){
                javax.swing.JOptionPane.showMessageDialog(this, "Tarif Konsultasi harus berupa angka!");
                return;
            }

            // Dialog Konfirmasi dengan YES_NO_CANCEL_OPTION
            int confirm = javax.swing.JOptionPane.showConfirmDialog(
                this, 
                "Apakah Anda yakin ingin melakukan aksi " + action + " pada data Dokter ini?", 
                "Konfirmasi Simpan", 
                javax.swing.JOptionPane.YES_NO_CANCEL_OPTION
            );

            if (confirm != javax.swing.JOptionPane.YES_OPTION) {
                return; 
            }

            String nama = inputNamaDokterTextField.getText();
            String noSTR = inputNomorSTRTextField.getText();
            String spesialis = inputSpesialisasiDokterTextField.getText();
            double tarif = Double.parseDouble(inputTarifDokterTextField.getText());
            
            // AUTO GENERATE data yang formnya tidak tersedia di UI
            String idDokter = action.equals("tambah") ? "DKT-" + System.currentTimeMillis() : selectedId;
            String noTelepon = "-"; // Dummy
            String username = nama.replaceAll("\\s+", "").toLowerCase(); // Dummy dari nama
            String password = "123"; // Dummy

            model.Dokter d = new model.Dokter(idDokter, noSTR, nama, noTelepon, spesialis, tarif, username, password);
            d.setStatusAktif(statusAktif);

            if(action.equals("tambah")) {
                dokterControl.insert(d);
            } else if(action.equals("ubah")) {
                dokterControl.update(d, selectedId);
            }

            clearTextDokter();
            setComponentsDokter(false);
            setEditDeleteButtonDokter(false);
            tambahDokterButton.setEnabled(true);
            showDokter();
            
            selectedId = null;
            action = null;

        } catch(Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_simpanDokterButtonActionPerformed

    private void pencarianDokterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pencarianDokterButtonActionPerformed
        doSearchDokter();
    }//GEN-LAST:event_pencarianDokterButtonActionPerformed

    private void pencarianDokterTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pencarianDokterTextFieldKeyPressed
        if(evt.getKeyChar() == '\n') doSearchDokter();
    }//GEN-LAST:event_pencarianDokterTextFieldKeyPressed

    private void dokterScrollPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dokterScrollPaneMouseClicked
        
    }//GEN-LAST:event_dokterScrollPaneMouseClicked

    private void dokterTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dokterTableMouseClicked
        int clickedRow = dokterTable.getSelectedRow();
        if(clickedRow < 0) return;

        javax.swing.table.TableModel tableModel = dokterTable.getModel();

        setComponentsDokter(false); 
        setEditDeleteButtonDokter(true);
        tambahDokterButton.setEnabled(true);

       
        Object idVal = tableModel.getValueAt(clickedRow, 0);
        selectedId = idVal != null ? idVal.toString() : "";
        
        Object namaVal = tableModel.getValueAt(clickedRow, 1);
        inputNamaDokterTextField.setText(namaVal != null ? namaVal.toString() : "");
        
        Object strVal = tableModel.getValueAt(clickedRow, 2);
        inputNomorSTRTextField.setText(strVal != null ? strVal.toString() : "");
        
        Object spesialisVal = tableModel.getValueAt(clickedRow, 3);
        inputSpesialisasiDokterTextField.setText(spesialisVal != null ? spesialisVal.toString() : "");
        
        Object tarifVal = tableModel.getValueAt(clickedRow, 4);
        inputTarifDokterTextField.setText(tarifVal != null ? tarifVal.toString() : "");
        
        Object statusVal = tableModel.getValueAt(clickedRow, 5);
        if(statusVal != null && statusVal.toString().equals("Aktif")) {
            statusAktif = true;
            inputStatusDokterButton.setText("Aktif");
        } else {
            statusAktif = false;
            inputStatusDokterButton.setText("Tidak Aktif");
        }
    }//GEN-LAST:event_dokterTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barukanDokterButton;
    private javax.swing.JButton batalDokterButton;
    private javax.swing.JPanel dokterButtonPanel;
    private javax.swing.JScrollPane dokterScrollPane;
    private javax.swing.JTable dokterTable;
    private javax.swing.JPanel formInputDokterPanel;
    private javax.swing.JButton hapusDokterButton;
    private javax.swing.JLabel inputDokterLabel;
    private javax.swing.JLabel inputNamaDokterLabel;
    private javax.swing.JPanel inputNamaDokterPanel;
    private javax.swing.JTextField inputNamaDokterTextField;
    private javax.swing.JLabel inputNomorSTRLabel;
    private javax.swing.JPanel inputNomorSTRPanel;
    private javax.swing.JTextField inputNomorSTRTextField;
    private javax.swing.JLabel inputSpesialisasiDokterLabel;
    private javax.swing.JPanel inputSpesialisasiDokterPanel;
    private javax.swing.JTextField inputSpesialisasiDokterTextField;
    private javax.swing.JButton inputStatusDokterButton;
    private javax.swing.JLabel inputStatusDokterLabel;
    private javax.swing.JPanel inputStatusDokterPanel;
    private javax.swing.JLabel inputTarifDokterLabel;
    private javax.swing.JPanel inputTarifDokterPanel;
    private javax.swing.JTextField inputTarifDokterTextField;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton pencarianDokterButton;
    private javax.swing.JLabel pencarianDokterLabel;
    private javax.swing.JPanel pencarianDokterPanel;
    private javax.swing.JTextField pencarianDokterTextField;
    private javax.swing.JButton simpanDokterButton;
    private javax.swing.JButton tambahDokterButton;
    // End of variables declaration//GEN-END:variables
}
