/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panelView;

import control.DokterControl;
import control.JadwalDokterControl;
import control.PoliklinikControl;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Dokter;
import model.JadwalDokter;
import model.Poliklinik;

public class ManajemenJadwalDokterPanel extends javax.swing.JPanel {

    private final JadwalDokterControl jdc = new JadwalDokterControl();
    private final DokterControl dc = new DokterControl();
    private final PoliklinikControl pkc = new PoliklinikControl();
    private List<Dokter> dokterList;
    private List<Poliklinik> poliklinikList;
    private String action = null;
    private String selectedId = null;
    

    public ManajemenJadwalDokterPanel() {
        initComponents();
        setOpaque(false);

        setupTable();
        loadDokterComboBox();
        loadPoliklinikComboBox();
        setupJamFilter(inputJamMulaiTextField);
        setupJamFilter(inputJamSelesaiTextField);
        setupKuotaFilter();

        setFormEnabled(false);
        setEditDeleteEnabled(false);
        showJadwal();
        
        

        pencarianJadwalButton.addActionListener(e -> doSearch());
        pencarianJadwalTextField.addActionListener(e -> doSearch());

        

        

        simpanJadwalButton.addActionListener(e -> simpanJadwal());

        jadwalTable.getSelectionModel().addListSelectionListener(e -> {
            if (e.getValueIsAdjusting()) return;
            int row = jadwalTable.getSelectedRow();
            if (row < 0) return;
            selectedId = (String) jadwalTable.getValueAt(row, 0);
            JadwalDokter j = jdc.search(selectedId);
            if (j != null) {
                fillForm(j);
                setEditDeleteEnabled(true);
                setFormEnabled(false);
                action = null;
            }
        });
    }
    
    public void setFormEnabled(boolean value) {
        inputIdJadwalTextField.setEnabled(false);
        inputJamMulaiTextField.setEnabled(value);
        inputJamSelesaiTextField.setEnabled(value);
        inputKuotaPasienTextField.setEnabled(value);
        pilihDokterDropDown.setEnabled(value);
        pilihPoliKlinikDropDown.setEnabled(value);
        simpanJadwalButton.setEnabled(value);
        batalJadwalButton.setEnabled(value);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        pencarianJadwalPanel = new javax.swing.JPanel();
        pencarianJadwalLabel = new javax.swing.JLabel();
        pencarianJadwalTextField = new javax.swing.JTextField();
        pencarianJadwalButton = new javax.swing.JButton();
        formInputDataJadwalPanel = new javax.swing.JPanel();
        InputDataJadwalLabel = new javax.swing.JLabel();
        inputIdJadwalPanel = new javax.swing.JPanel();
        inputIdJadwalLabel = new javax.swing.JLabel();
        inputIdJadwalTextField = new javax.swing.JTextField();
        pilihDokterPanel = new javax.swing.JPanel();
        pilihDokterLabel = new javax.swing.JLabel();
        pilihDokterDropDown = new javax.swing.JComboBox<>();
        inputJamMulaiPanel = new javax.swing.JPanel();
        inputJamMulaiLabel = new javax.swing.JLabel();
        inputJamMulaiTextField = new javax.swing.JTextField();
        simpanJadwalButton = new javax.swing.JButton();
        batalJadwalButton = new javax.swing.JButton();
        pilihPoliKlinikPanel = new javax.swing.JPanel();
        pilihPoliKlinikLabel = new javax.swing.JLabel();
        pilihPoliKlinikDropDown = new javax.swing.JComboBox<>();
        inputKuotaPasienPanel = new javax.swing.JPanel();
        inputKuotaPasienLabel = new javax.swing.JLabel();
        inputKuotaPasienTextField = new javax.swing.JTextField();
        inputJamSelesaiPanel = new javax.swing.JPanel();
        inputJamSelesaiLabel = new javax.swing.JLabel();
        inputJamSelesaiTextField = new javax.swing.JTextField();
        jadwalScrollPane = new javax.swing.JScrollPane();
        jadwalTable = new javax.swing.JTable();
        jadwalButtonPanel = new javax.swing.JPanel();
        tambahJadwalButton = new javax.swing.JButton();
        barukanJadwalButton = new javax.swing.JButton();
        hapusJadwalButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(238, 239, 253));
        setPreferredSize(new java.awt.Dimension(1224, 811));

        mainPanel.setBackground(new java.awt.Color(238, 239, 253));

        pencarianJadwalPanel.setBackground(new java.awt.Color(255, 255, 255));
        pencarianJadwalPanel.setPreferredSize(new java.awt.Dimension(800, 70));

        pencarianJadwalLabel.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        pencarianJadwalLabel.setText("Pencarian Jadwal");

        pencarianJadwalTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pencarianJadwalTextFieldKeyPressed(evt);
            }
        });

        pencarianJadwalButton.setText("Cari");
        pencarianJadwalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pencarianJadwalButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pencarianJadwalPanelLayout = new javax.swing.GroupLayout(pencarianJadwalPanel);
        pencarianJadwalPanel.setLayout(pencarianJadwalPanelLayout);
        pencarianJadwalPanelLayout.setHorizontalGroup(
            pencarianJadwalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pencarianJadwalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pencarianJadwalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pencarianJadwalLabel)
                    .addGroup(pencarianJadwalPanelLayout.createSequentialGroup()
                        .addComponent(pencarianJadwalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 1038, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pencarianJadwalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pencarianJadwalPanelLayout.setVerticalGroup(
            pencarianJadwalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pencarianJadwalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pencarianJadwalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pencarianJadwalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pencarianJadwalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pencarianJadwalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        formInputDataJadwalPanel.setBackground(new java.awt.Color(255, 255, 255));

        InputDataJadwalLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        InputDataJadwalLabel.setText("Data Jadwal Dokter");

        inputIdJadwalPanel.setBackground(new java.awt.Color(255, 255, 255));

        inputIdJadwalLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        inputIdJadwalLabel.setText("ID Jadwal");

        javax.swing.GroupLayout inputIdJadwalPanelLayout = new javax.swing.GroupLayout(inputIdJadwalPanel);
        inputIdJadwalPanel.setLayout(inputIdJadwalPanelLayout);
        inputIdJadwalPanelLayout.setHorizontalGroup(
            inputIdJadwalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputIdJadwalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputIdJadwalLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(inputIdJadwalTextField, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        inputIdJadwalPanelLayout.setVerticalGroup(
            inputIdJadwalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputIdJadwalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputIdJadwalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inputIdJadwalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pilihDokterPanel.setBackground(new java.awt.Color(255, 255, 255));

        pilihDokterLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        pilihDokterLabel.setText("Pilih Dokter");

        pilihDokterDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pilihDokterPanelLayout = new javax.swing.GroupLayout(pilihDokterPanel);
        pilihDokterPanel.setLayout(pilihDokterPanelLayout);
        pilihDokterPanelLayout.setHorizontalGroup(
            pilihDokterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pilihDokterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pilihDokterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pilihDokterPanelLayout.createSequentialGroup()
                        .addComponent(pilihDokterLabel)
                        .addContainerGap(281, Short.MAX_VALUE))
                    .addComponent(pilihDokterDropDown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pilihDokterPanelLayout.setVerticalGroup(
            pilihDokterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pilihDokterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pilihDokterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pilihDokterDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        inputJamMulaiPanel.setBackground(new java.awt.Color(255, 255, 255));

        inputJamMulaiLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        inputJamMulaiLabel.setText("Jam Mulai");

        javax.swing.GroupLayout inputJamMulaiPanelLayout = new javax.swing.GroupLayout(inputJamMulaiPanel);
        inputJamMulaiPanel.setLayout(inputJamMulaiPanelLayout);
        inputJamMulaiPanelLayout.setHorizontalGroup(
            inputJamMulaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputJamMulaiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputJamMulaiLabel)
                .addContainerGap(312, Short.MAX_VALUE))
            .addComponent(inputJamMulaiTextField, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        inputJamMulaiPanelLayout.setVerticalGroup(
            inputJamMulaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputJamMulaiPanelLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(inputJamMulaiLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputJamMulaiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        simpanJadwalButton.setBackground(new java.awt.Color(51, 178, 73));
        simpanJadwalButton.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        simpanJadwalButton.setForeground(new java.awt.Color(255, 255, 255));
        simpanJadwalButton.setText("Simpan");
        simpanJadwalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanJadwalButtonActionPerformed(evt);
            }
        });

        batalJadwalButton.setBackground(new java.awt.Color(237, 8, 0));
        batalJadwalButton.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        batalJadwalButton.setForeground(new java.awt.Color(255, 255, 255));
        batalJadwalButton.setText("Batal");
        batalJadwalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalJadwalButtonActionPerformed(evt);
            }
        });

        pilihPoliKlinikPanel.setBackground(new java.awt.Color(255, 255, 255));

        pilihPoliKlinikLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        pilihPoliKlinikLabel.setText("Pilih Poliklinik");

        pilihPoliKlinikDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pilihPoliKlinikPanelLayout = new javax.swing.GroupLayout(pilihPoliKlinikPanel);
        pilihPoliKlinikPanel.setLayout(pilihPoliKlinikPanelLayout);
        pilihPoliKlinikPanelLayout.setHorizontalGroup(
            pilihPoliKlinikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pilihPoliKlinikPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pilihPoliKlinikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pilihPoliKlinikPanelLayout.createSequentialGroup()
                        .addComponent(pilihPoliKlinikLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pilihPoliKlinikDropDown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pilihPoliKlinikPanelLayout.setVerticalGroup(
            pilihPoliKlinikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pilihPoliKlinikPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pilihPoliKlinikLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pilihPoliKlinikDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        inputKuotaPasienPanel.setBackground(new java.awt.Color(255, 255, 255));

        inputKuotaPasienLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        inputKuotaPasienLabel.setText("Kuota Pasien");

        inputKuotaPasienTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputKuotaPasienTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputKuotaPasienPanelLayout = new javax.swing.GroupLayout(inputKuotaPasienPanel);
        inputKuotaPasienPanel.setLayout(inputKuotaPasienPanelLayout);
        inputKuotaPasienPanelLayout.setHorizontalGroup(
            inputKuotaPasienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputKuotaPasienPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputKuotaPasienLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(inputKuotaPasienTextField, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        inputKuotaPasienPanelLayout.setVerticalGroup(
            inputKuotaPasienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputKuotaPasienPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(inputKuotaPasienLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputKuotaPasienTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        inputJamSelesaiPanel.setBackground(new java.awt.Color(255, 255, 255));

        inputJamSelesaiLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        inputJamSelesaiLabel.setText("Jam selesai");

        javax.swing.GroupLayout inputJamSelesaiPanelLayout = new javax.swing.GroupLayout(inputJamSelesaiPanel);
        inputJamSelesaiPanel.setLayout(inputJamSelesaiPanelLayout);
        inputJamSelesaiPanelLayout.setHorizontalGroup(
            inputJamSelesaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputJamSelesaiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputJamSelesaiLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(inputJamSelesaiTextField, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        inputJamSelesaiPanelLayout.setVerticalGroup(
            inputJamSelesaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputJamSelesaiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputJamSelesaiLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inputJamSelesaiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout formInputDataJadwalPanelLayout = new javax.swing.GroupLayout(formInputDataJadwalPanel);
        formInputDataJadwalPanel.setLayout(formInputDataJadwalPanelLayout);
        formInputDataJadwalPanelLayout.setHorizontalGroup(
            formInputDataJadwalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formInputDataJadwalPanelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(formInputDataJadwalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formInputDataJadwalPanelLayout.createSequentialGroup()
                        .addComponent(InputDataJadwalLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formInputDataJadwalPanelLayout.createSequentialGroup()
                        .addGroup(formInputDataJadwalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, formInputDataJadwalPanelLayout.createSequentialGroup()
                                .addGroup(formInputDataJadwalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(inputIdJadwalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(inputJamMulaiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(formInputDataJadwalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pilihDokterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(inputJamSelesaiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(formInputDataJadwalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pilihPoliKlinikPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(inputKuotaPasienPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(formInputDataJadwalPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(simpanJadwalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(batalJadwalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))))
        );
        formInputDataJadwalPanelLayout.setVerticalGroup(
            formInputDataJadwalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formInputDataJadwalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InputDataJadwalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formInputDataJadwalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(formInputDataJadwalPanelLayout.createSequentialGroup()
                        .addComponent(pilihPoliKlinikPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inputKuotaPasienPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formInputDataJadwalPanelLayout.createSequentialGroup()
                        .addGroup(formInputDataJadwalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputIdJadwalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pilihDokterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(formInputDataJadwalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formInputDataJadwalPanelLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(inputJamSelesaiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(formInputDataJadwalPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inputJamMulaiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formInputDataJadwalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanJadwalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(batalJadwalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jadwalTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jadwalScrollPane.setViewportView(jadwalTable);

        jadwalButtonPanel.setBackground(new java.awt.Color(255, 255, 255));

        tambahJadwalButton.setBackground(new java.awt.Color(51, 178, 73));
        tambahJadwalButton.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        tambahJadwalButton.setForeground(new java.awt.Color(255, 255, 255));
        tambahJadwalButton.setText("Tambah");
        tambahJadwalButton.setPreferredSize(new java.awt.Dimension(124, 24));
        tambahJadwalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahJadwalButtonActionPerformed(evt);
            }
        });

        barukanJadwalButton.setBackground(new java.awt.Color(255, 189, 3));
        barukanJadwalButton.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        barukanJadwalButton.setForeground(new java.awt.Color(255, 255, 255));
        barukanJadwalButton.setText("Barukan");
        barukanJadwalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barukanJadwalButtonActionPerformed(evt);
            }
        });

        hapusJadwalButton.setBackground(new java.awt.Color(237, 8, 0));
        hapusJadwalButton.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        hapusJadwalButton.setForeground(new java.awt.Color(255, 255, 255));
        hapusJadwalButton.setText("Hapus");
        hapusJadwalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusJadwalButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jadwalButtonPanelLayout = new javax.swing.GroupLayout(jadwalButtonPanel);
        jadwalButtonPanel.setLayout(jadwalButtonPanelLayout);
        jadwalButtonPanelLayout.setHorizontalGroup(
            jadwalButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jadwalButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambahJadwalButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barukanJadwalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hapusJadwalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jadwalButtonPanelLayout.setVerticalGroup(
            jadwalButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jadwalButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jadwalButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tambahJadwalButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(barukanJadwalButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapusJadwalButton, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pencarianJadwalPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1141, Short.MAX_VALUE)
                    .addComponent(jadwalButtonPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(formInputDataJadwalPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jadwalScrollPane))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pencarianJadwalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jadwalButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(formInputDataJadwalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jadwalScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inputKuotaPasienTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputKuotaPasienTextFieldActionPerformed
    }//GEN-LAST:event_inputKuotaPasienTextFieldActionPerformed

    private void tambahJadwalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahJadwalButtonActionPerformed
        action = "tambah";
        clearForm();
        inputIdJadwalTextField.setText(jdc.generateId());
        setFormEnabled(true);
        setEditDeleteEnabled(false);
    }//GEN-LAST:event_tambahJadwalButtonActionPerformed

    private void barukanJadwalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barukanJadwalButtonActionPerformed
        action = "update";
        setFormEnabled(true);
        inputIdJadwalTextField.setEnabled(false);
    }//GEN-LAST:event_barukanJadwalButtonActionPerformed

    private void hapusJadwalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusJadwalButtonActionPerformed
        action = "hapus";
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus data Dokter ini?", "Konfirmasi Hapus", javax.swing.JOptionPane.YES_NO_OPTION);
        
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            jdc.delete(selectedId); 
            clearForm();
            setFormEnabled(false);
            setEditDeleteEnabled(false);
            showJadwal();
            tambahJadwalButton.setEnabled(true);
        }
    }//GEN-LAST:event_hapusJadwalButtonActionPerformed

    private void simpanJadwalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanJadwalButtonActionPerformed
        simpanJadwal();
    }//GEN-LAST:event_simpanJadwalButtonActionPerformed

    private void batalJadwalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalJadwalButtonActionPerformed
        action = null;
        selectedId = null;
        clearForm();
        setFormEnabled(false);
        setEditDeleteEnabled(false);
        tambahJadwalButton.setEnabled(true);
    }//GEN-LAST:event_batalJadwalButtonActionPerformed

    private void pencarianJadwalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pencarianJadwalButtonActionPerformed
        doSearch();
    }//GEN-LAST:event_pencarianJadwalButtonActionPerformed

    private void pencarianJadwalTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pencarianJadwalTextFieldKeyPressed
        if(evt.getKeyChar() == '\n') doSearch();
    }//GEN-LAST:event_pencarianJadwalTextFieldKeyPressed

    // -------------------------------------------------------------------------

    
    private void setupTable() {
        DefaultTableModel m = new DefaultTableModel(
            new String[]{"ID Jadwal", "Nama Dokter", "Jam Mulai", "Jam Selesai", "Poliklinik", "Kuota"}, 0
        ) { @Override public boolean isCellEditable(int r, int c) { return false; } };
        jadwalTable.setModel(m);
    }

    private void loadDokterComboBox() {
        dokterList = dc.showData();
        javax.swing.DefaultComboBoxModel<String> m = new javax.swing.DefaultComboBoxModel<>();
        m.addElement("-- Pilih Dokter --");
        for (Dokter d : dokterList) m.addElement(d.getId() + " - " + d.getNama());
        pilihDokterDropDown.setModel(m);
    }

    private void loadPoliklinikComboBox() {
        poliklinikList = pkc.showData();
        javax.swing.DefaultComboBoxModel<String> m = new javax.swing.DefaultComboBoxModel<>();
        m.addElement("-- Pilih Poliklinik --");
        for (Poliklinik p : poliklinikList) m.addElement(p.getIdPoliklinik() + " - " + p.getNamaPoliklinik());
        pilihPoliKlinikDropDown.setModel(m);
    }

    private void showJadwal() {
        DefaultTableModel m = (DefaultTableModel) jadwalTable.getModel();
        m.setRowCount(0);
        for (Object[] row : jdc.showDataWithNames()) m.addRow(row);
    }

    

    private void setEditDeleteEnabled(boolean value) {
        barukanJadwalButton.setEnabled(value);
        hapusJadwalButton.setEnabled(value);
    }

    private void clearForm() {
        inputIdJadwalTextField.setText("");
        pilihDokterDropDown.setSelectedIndex(0);
        pilihPoliKlinikDropDown.setSelectedIndex(0);
        inputJamMulaiTextField.setText("");
        inputJamSelesaiTextField.setText("");
        inputKuotaPasienTextField.setText("");
    }

    private void fillForm(JadwalDokter j) {
        inputIdJadwalTextField.setText(j.getIdJadwal());
        pilihDokterDropDown.setSelectedIndex(0);
        for (int i = 1; i < pilihDokterDropDown.getItemCount(); i++) {
            if (((String) pilihDokterDropDown.getItemAt(i)).startsWith(j.getIdDokter() + " - ")) {
                pilihDokterDropDown.setSelectedIndex(i); break;
            }
        }
        pilihPoliKlinikDropDown.setSelectedIndex(0);
        for (int i = 1; i < pilihPoliKlinikDropDown.getItemCount(); i++) {
            if (((String) pilihPoliKlinikDropDown.getItemAt(i)).startsWith(j.getIdPoliklinik() + " - ")) {
                pilihPoliKlinikDropDown.setSelectedIndex(i); break;
            }
        }
        inputJamMulaiTextField.setText(j.getJamMulai() != null ? j.getJamMulai() : "");
        inputJamSelesaiTextField.setText(j.getJamSelesai() != null ? j.getJamSelesai() : "");
        inputKuotaPasienTextField.setText(String.valueOf(j.getKuotaPasien()));
    }

    private void doSearch() {
        String keyword = pencarianJadwalTextField.getText().trim();
        DefaultTableModel m = (DefaultTableModel) jadwalTable.getModel();
        if (keyword.isEmpty()) {
            showJadwal(); clearForm(); selectedId = null; action = null;
            setFormEnabled(false); setEditDeleteEnabled(false); return;
        }
        m.setRowCount(0);
        selectedId = null; setEditDeleteEnabled(false); setFormEnabled(false); clearForm();
        List<Object[]> hasil = jdc.searchByKeyword(keyword);
        if (hasil.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Jadwal tidak ditemukan.", "Tidak Ditemukan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        for (Object[] row : hasil) m.addRow(row);
        if (hasil.size() == 1) {
            JadwalDokter j = jdc.search((String) hasil.get(0)[0]);
            if (j != null) { fillForm(j); selectedId = j.getIdJadwal(); setEditDeleteEnabled(true); }
        }
    }

    private void simpanJadwal() {
        if (action == null) return;
        String id = inputIdJadwalTextField.getText().trim();
        String jamMulai = inputJamMulaiTextField.getText().trim();
        String jamSelesai = inputJamSelesaiTextField.getText().trim();
        String kuotaStr = inputKuotaPasienTextField.getText().trim();

        if (id.isEmpty() || jamMulai.isEmpty() || jamSelesai.isEmpty() || kuotaStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua field wajib diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE); return;
        }
        if (!isValidJam(jamMulai) || !isValidJam(jamSelesai)) {
            JOptionPane.showMessageDialog(this, "Format jam tidak valid. Gunakan HH:mm.", "Peringatan", JOptionPane.WARNING_MESSAGE); return;
        }
        if (jamMulai.compareTo(jamSelesai) >= 0) {
            JOptionPane.showMessageDialog(this, "Jam mulai harus lebih awal dari jam selesai.", "Peringatan", JOptionPane.WARNING_MESSAGE); return;
        }

        String selDokter = (String) pilihDokterDropDown.getSelectedItem();
        if (selDokter == null || selDokter.startsWith("--")) {
            JOptionPane.showMessageDialog(this, "Pilih dokter terlebih dahulu.", "Peringatan", JOptionPane.WARNING_MESSAGE); return;
        }
        String selPoli = (String) pilihPoliKlinikDropDown.getSelectedItem();
        if (selPoli == null || selPoli.startsWith("--")) {
            JOptionPane.showMessageDialog(this, "Pilih poliklinik terlebih dahulu.", "Peringatan", JOptionPane.WARNING_MESSAGE); return;
        }

        int kuota;
        try { kuota = Integer.parseInt(kuotaStr); if (kuota <= 0) throw new NumberFormatException(); }
        catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Kuota pasien harus angka positif.", "Peringatan", JOptionPane.WARNING_MESSAGE); return;
        }

        String idDokter = selDokter.split(" - ")[0];
        String idPoli   = selPoli.split(" - ")[0];

        int opsi = JOptionPane.showConfirmDialog(this,
            "Yakin ingin " + ("add".equals(action) ? "tambah" : "update") + " jadwal?",
            "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (opsi != JOptionPane.YES_OPTION) return;

        JadwalDokter j = new JadwalDokter(id, idDokter, idPoli, jamMulai, jamSelesai, kuota);
        if ("tambah".equals(action)) { jdc.insert(j); JOptionPane.showMessageDialog(this, "Jadwal berhasil ditambahkan."); }
        else { jdc.update(j, selectedId); JOptionPane.showMessageDialog(this, "Jadwal berhasil diupdate."); }

        action = null; selectedId = null;
        clearForm(); setFormEnabled(false); setEditDeleteEnabled(false);
        showJadwal();
    }

    private boolean isValidJam(String jam) {
        if (!jam.matches("\\d{2}:\\d{2}")) return false;
        int h = Integer.parseInt(jam.substring(0, 2));
        int m = Integer.parseInt(jam.substring(3));
        return h <= 23 && m <= 59;
    }

    private void setupJamFilter(javax.swing.JTextField field) {
        ((javax.swing.text.AbstractDocument) field.getDocument())
            .setDocumentFilter(new javax.swing.text.DocumentFilter() {
                @Override
                public void replace(javax.swing.text.DocumentFilter.FilterBypass fb,
                        int off, int len, String str, javax.swing.text.AttributeSet a)
                        throws javax.swing.text.BadLocationException {
                    if (str == null) str = "";
                    String digits = str.replaceAll("[^0-9]", "");
                    String current = fb.getDocument().getText(0, fb.getDocument().getLength());
                    String after = current.substring(0, off) + digits + current.substring(off + len);
                    String raw = after.replace(":", "");
                    if (raw.length() > 4) raw = raw.substring(0, 4);
                    String formatted = raw.length() >= 3 ? raw.substring(0, 2) + ":" + raw.substring(2) : raw;
                    fb.replace(0, fb.getDocument().getLength(), formatted, a);
                }
                @Override
                public void insertString(javax.swing.text.DocumentFilter.FilterBypass fb,
                        int off, String str, javax.swing.text.AttributeSet a)
                        throws javax.swing.text.BadLocationException { replace(fb, off, 0, str, a); }
            });
    }

    private void setupKuotaFilter() {
        ((javax.swing.text.AbstractDocument) inputKuotaPasienTextField.getDocument())
            .setDocumentFilter(new javax.swing.text.DocumentFilter() {
                @Override
                public void insertString(javax.swing.text.DocumentFilter.FilterBypass fb,
                        int off, String str, javax.swing.text.AttributeSet a)
                        throws javax.swing.text.BadLocationException {
                    if (str != null && str.matches("[0-9]+")) super.insertString(fb, off, str, a);
                }
                @Override
                public void replace(javax.swing.text.DocumentFilter.FilterBypass fb,
                        int off, int len, String str, javax.swing.text.AttributeSet a)
                        throws javax.swing.text.BadLocationException {
                    if (str == null || str.matches("[0-9]*")) super.replace(fb, off, len, str, a);
                }
            });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel InputDataJadwalLabel;
    private javax.swing.JButton barukanJadwalButton;
    private javax.swing.JButton batalJadwalButton;
    private javax.swing.JPanel formInputDataJadwalPanel;
    private javax.swing.JButton hapusJadwalButton;
    private javax.swing.JLabel inputIdJadwalLabel;
    private javax.swing.JPanel inputIdJadwalPanel;
    private javax.swing.JTextField inputIdJadwalTextField;
    private javax.swing.JLabel inputJamMulaiLabel;
    private javax.swing.JPanel inputJamMulaiPanel;
    private javax.swing.JTextField inputJamMulaiTextField;
    private javax.swing.JLabel inputJamSelesaiLabel;
    private javax.swing.JPanel inputJamSelesaiPanel;
    private javax.swing.JTextField inputJamSelesaiTextField;
    private javax.swing.JLabel inputKuotaPasienLabel;
    private javax.swing.JPanel inputKuotaPasienPanel;
    private javax.swing.JTextField inputKuotaPasienTextField;
    private javax.swing.JPanel jadwalButtonPanel;
    private javax.swing.JScrollPane jadwalScrollPane;
    private javax.swing.JTable jadwalTable;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton pencarianJadwalButton;
    private javax.swing.JLabel pencarianJadwalLabel;
    private javax.swing.JPanel pencarianJadwalPanel;
    private javax.swing.JTextField pencarianJadwalTextField;
    private javax.swing.JComboBox<String> pilihDokterDropDown;
    private javax.swing.JLabel pilihDokterLabel;
    private javax.swing.JPanel pilihDokterPanel;
    private javax.swing.JComboBox<String> pilihPoliKlinikDropDown;
    private javax.swing.JLabel pilihPoliKlinikLabel;
    private javax.swing.JPanel pilihPoliKlinikPanel;
    private javax.swing.JButton simpanJadwalButton;
    private javax.swing.JButton tambahJadwalButton;
    // End of variables declaration//GEN-END:variables
}
