/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panelView;

public class ManajemenKunjunganPanel extends javax.swing.JPanel {

    public ManajemenKunjunganPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        formInputDataKunjunganPanel = new javax.swing.JPanel();
        formInputDataKunjunganLabel = new javax.swing.JLabel();
        inputIdKunjunganPanel = new javax.swing.JPanel();
        inputIdKunjunganLabel = new javax.swing.JLabel();
        inputIdKunjunganTextField = new javax.swing.JTextField();
        inputNomorRekamMedisPanel = new javax.swing.JPanel();
        inputNomorRekamMedisLabel = new javax.swing.JLabel();
        inputNomorRekamMedisTextField = new javax.swing.JTextField();
        inputTanggalKunjunganPanel = new javax.swing.JPanel();
        inputTanggalKunjunganLabel = new javax.swing.JLabel();
        inputTanggalKunjunganDateChooser = new com.toedter.calendar.JDateChooser();
        batalButton = new javax.swing.JButton();
        inputPilihDokterPanel = new javax.swing.JPanel();
        inputPilihDokterLabel = new javax.swing.JLabel();
        inputPilihDokterComboBox = new javax.swing.JComboBox<>();
        inputJamKunjunganPanel = new javax.swing.JPanel();
        inputJamKunjunganLabel = new javax.swing.JLabel();
        inputJamKunjunganTextField = new javax.swing.JTextField();
        inputStatusKunjunganPanel = new javax.swing.JPanel();
        inputStatusKunjunganLabel = new javax.swing.JLabel();
        inputStatusKunjunganComboBox = new javax.swing.JComboBox<>();
        inputIdDiagnosaPanel = new javax.swing.JPanel();
        inputIdDiagnosaLabel = new javax.swing.JLabel();
        inputIdDiagnosaTextField = new javax.swing.JTextField();
        inputIdResepPanel = new javax.swing.JPanel();
        inputIdResepLabel = new javax.swing.JLabel();
        inputIdResepTextField = new javax.swing.JTextField();
        inputBiayaKonsultasiPanel = new javax.swing.JPanel();
        inputBiayaKonsultasiLabel = new javax.swing.JLabel();
        inputBiayaKonsultasiTextField = new javax.swing.JTextField();
        inputKeluhanUtamaPanel = new javax.swing.JPanel();
        inputKeluhanUtamaLabel = new javax.swing.JLabel();
        inputKeluhanUtamaScrollPane = new javax.swing.JScrollPane();
        inputKeluhanUtamaTextField = new javax.swing.JTextField();
        simpanButton = new javax.swing.JButton();
        inputHasilPemeriksaanPanel = new javax.swing.JPanel();
        inputHasilPemeriksaanLabel = new javax.swing.JLabel();
        inputHasilPemeriksaanScrollPane = new javax.swing.JScrollPane();
        inputHasilPemeriksaanTextField = new javax.swing.JTextField();
        searchKunjunganPanel = new javax.swing.JPanel();
        judulKunjunganLabel = new javax.swing.JLabel();
        subJudulKunjunganLabel = new javax.swing.JLabel();
        searchKunjunganTextField = new javax.swing.JTextField();
        searchKunjunganButton = new javax.swing.JButton();
        searchKunjunganLabel = new javax.swing.JLabel();
        metricCardPanel = new javax.swing.JPanel();
        antrianCardPanel = new javax.swing.JPanel();
        antrianCardLabel = new javax.swing.JLabel();
        antrianNumber = new javax.swing.JLabel();
        kunjunganSelesaiCardPanel = new javax.swing.JPanel();
        kunjunganSelesaiCardLabel = new javax.swing.JLabel();
        kunjunganAntrianNumber = new javax.swing.JLabel();
        totalPendapatanCardPanel = new javax.swing.JPanel();
        totalPendapatanCardLabel = new javax.swing.JLabel();
        totalPendapatanNumber = new javax.swing.JLabel();
        kunjunganScrollPane = new javax.swing.JScrollPane();
        kunjunganTable = new javax.swing.JTable();
        kunjunganButtonPanel = new javax.swing.JPanel();
        tanbahKunjunganButton = new javax.swing.JButton();
        barukanKunjunganButton = new javax.swing.JButton();
        hapusKunjunganButton = new javax.swing.JButton();
        kunjunganButtonLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(238, 239, 253));
        setPreferredSize(new java.awt.Dimension(1224, 811));

        mainPanel.setBackground(new java.awt.Color(238, 239, 253));

        formInputDataKunjunganPanel.setBackground(new java.awt.Color(255, 255, 255));

        formInputDataKunjunganLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        formInputDataKunjunganLabel.setText("Data Kunjungan");

        inputIdKunjunganPanel.setBackground(new java.awt.Color(255, 255, 255));

        inputIdKunjunganLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        inputIdKunjunganLabel.setText("ID Kunjungan");

        javax.swing.GroupLayout inputIdKunjunganPanelLayout = new javax.swing.GroupLayout(inputIdKunjunganPanel);
        inputIdKunjunganPanel.setLayout(inputIdKunjunganPanelLayout);
        inputIdKunjunganPanelLayout.setHorizontalGroup(
            inputIdKunjunganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputIdKunjunganPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputIdKunjunganLabel)
                .addContainerGap(171, Short.MAX_VALUE))
            .addGroup(inputIdKunjunganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(inputIdKunjunganPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(inputIdKunjunganTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        inputIdKunjunganPanelLayout.setVerticalGroup(
            inputIdKunjunganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputIdKunjunganPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputIdKunjunganLabel)
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(inputIdKunjunganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inputIdKunjunganPanelLayout.createSequentialGroup()
                    .addContainerGap(27, Short.MAX_VALUE)
                    .addComponent(inputIdKunjunganTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(16, 16, 16)))
        );

        inputNomorRekamMedisPanel.setBackground(new java.awt.Color(255, 255, 255));

        inputNomorRekamMedisLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        inputNomorRekamMedisLabel.setText("Nomor Rekam Medis");

        inputNomorRekamMedisTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNomorRekamMedisTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputNomorRekamMedisPanelLayout = new javax.swing.GroupLayout(inputNomorRekamMedisPanel);
        inputNomorRekamMedisPanel.setLayout(inputNomorRekamMedisPanelLayout);
        inputNomorRekamMedisPanelLayout.setHorizontalGroup(
            inputNomorRekamMedisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputNomorRekamMedisPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputNomorRekamMedisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputNomorRekamMedisPanelLayout.createSequentialGroup()
                        .addComponent(inputNomorRekamMedisLabel)
                        .addGap(0, 137, Short.MAX_VALUE))
                    .addComponent(inputNomorRekamMedisTextField))
                .addContainerGap())
        );
        inputNomorRekamMedisPanelLayout.setVerticalGroup(
            inputNomorRekamMedisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputNomorRekamMedisPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inputNomorRekamMedisLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputNomorRekamMedisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        inputTanggalKunjunganPanel.setBackground(new java.awt.Color(255, 255, 255));

        inputTanggalKunjunganLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        inputTanggalKunjunganLabel.setText("Tanggal");

        javax.swing.GroupLayout inputTanggalKunjunganPanelLayout = new javax.swing.GroupLayout(inputTanggalKunjunganPanel);
        inputTanggalKunjunganPanel.setLayout(inputTanggalKunjunganPanelLayout);
        inputTanggalKunjunganPanelLayout.setHorizontalGroup(
            inputTanggalKunjunganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputTanggalKunjunganPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputTanggalKunjunganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputTanggalKunjunganDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputTanggalKunjunganLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        inputTanggalKunjunganPanelLayout.setVerticalGroup(
            inputTanggalKunjunganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputTanggalKunjunganPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputTanggalKunjunganLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputTanggalKunjunganDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        batalButton.setBackground(new java.awt.Color(237, 8, 0));
        batalButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        batalButton.setForeground(new java.awt.Color(255, 255, 255));
        batalButton.setText("Batal");

        inputPilihDokterPanel.setBackground(new java.awt.Color(255, 255, 255));

        inputPilihDokterLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        inputPilihDokterLabel.setText("Pilih Dokter");

        inputPilihDokterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout inputPilihDokterPanelLayout = new javax.swing.GroupLayout(inputPilihDokterPanel);
        inputPilihDokterPanel.setLayout(inputPilihDokterPanelLayout);
        inputPilihDokterPanelLayout.setHorizontalGroup(
            inputPilihDokterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPilihDokterPanelLayout.createSequentialGroup()
                .addComponent(inputPilihDokterLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(inputPilihDokterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputPilihDokterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        inputPilihDokterPanelLayout.setVerticalGroup(
            inputPilihDokterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPilihDokterPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inputPilihDokterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPilihDokterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        inputJamKunjunganPanel.setBackground(new java.awt.Color(255, 255, 255));

        inputJamKunjunganLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        inputJamKunjunganLabel.setText("Jam");

        inputJamKunjunganTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputJamKunjunganTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputJamKunjunganPanelLayout = new javax.swing.GroupLayout(inputJamKunjunganPanel);
        inputJamKunjunganPanel.setLayout(inputJamKunjunganPanelLayout);
        inputJamKunjunganPanelLayout.setHorizontalGroup(
            inputJamKunjunganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputJamKunjunganPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputJamKunjunganLabel)
                .addContainerGap(229, Short.MAX_VALUE))
            .addGroup(inputJamKunjunganPanelLayout.createSequentialGroup()
                .addComponent(inputJamKunjunganTextField)
                .addContainerGap())
        );
        inputJamKunjunganPanelLayout.setVerticalGroup(
            inputJamKunjunganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputJamKunjunganPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inputJamKunjunganLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputJamKunjunganTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        inputStatusKunjunganPanel.setBackground(new java.awt.Color(255, 255, 255));

        inputStatusKunjunganLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        inputStatusKunjunganLabel.setText("Status Kunjungan");

        inputStatusKunjunganComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout inputStatusKunjunganPanelLayout = new javax.swing.GroupLayout(inputStatusKunjunganPanel);
        inputStatusKunjunganPanel.setLayout(inputStatusKunjunganPanelLayout);
        inputStatusKunjunganPanelLayout.setHorizontalGroup(
            inputStatusKunjunganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputStatusKunjunganPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputStatusKunjunganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputStatusKunjunganComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputStatusKunjunganLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        inputStatusKunjunganPanelLayout.setVerticalGroup(
            inputStatusKunjunganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputStatusKunjunganPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inputStatusKunjunganLabel)
                .addGap(8, 8, 8)
                .addComponent(inputStatusKunjunganComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        inputIdDiagnosaPanel.setBackground(new java.awt.Color(255, 255, 255));

        inputIdDiagnosaLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        inputIdDiagnosaLabel.setText("ID Diagnosa");

        javax.swing.GroupLayout inputIdDiagnosaPanelLayout = new javax.swing.GroupLayout(inputIdDiagnosaPanel);
        inputIdDiagnosaPanel.setLayout(inputIdDiagnosaPanelLayout);
        inputIdDiagnosaPanelLayout.setHorizontalGroup(
            inputIdDiagnosaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputIdDiagnosaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputIdDiagnosaLabel)
                .addContainerGap(179, Short.MAX_VALUE))
            .addGroup(inputIdDiagnosaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(inputIdDiagnosaPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(inputIdDiagnosaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        inputIdDiagnosaPanelLayout.setVerticalGroup(
            inputIdDiagnosaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputIdDiagnosaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputIdDiagnosaLabel)
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(inputIdDiagnosaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inputIdDiagnosaPanelLayout.createSequentialGroup()
                    .addContainerGap(27, Short.MAX_VALUE)
                    .addComponent(inputIdDiagnosaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(16, 16, 16)))
        );

        inputIdResepPanel.setBackground(new java.awt.Color(255, 255, 255));

        inputIdResepLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        inputIdResepLabel.setText("ID Resep");

        inputIdResepTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIdResepTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputIdResepPanelLayout = new javax.swing.GroupLayout(inputIdResepPanel);
        inputIdResepPanel.setLayout(inputIdResepPanelLayout);
        inputIdResepPanelLayout.setHorizontalGroup(
            inputIdResepPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputIdResepPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputIdResepPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputIdResepPanelLayout.createSequentialGroup()
                        .addComponent(inputIdResepLabel)
                        .addContainerGap(204, Short.MAX_VALUE))
                    .addComponent(inputIdResepTextField)))
        );
        inputIdResepPanelLayout.setVerticalGroup(
            inputIdResepPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputIdResepPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inputIdResepLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputIdResepTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        inputBiayaKonsultasiPanel.setBackground(new java.awt.Color(255, 255, 255));

        inputBiayaKonsultasiLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        inputBiayaKonsultasiLabel.setText("Biaya Konsultasi");

        inputBiayaKonsultasiTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBiayaKonsultasiTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputBiayaKonsultasiPanelLayout = new javax.swing.GroupLayout(inputBiayaKonsultasiPanel);
        inputBiayaKonsultasiPanel.setLayout(inputBiayaKonsultasiPanelLayout);
        inputBiayaKonsultasiPanelLayout.setHorizontalGroup(
            inputBiayaKonsultasiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputBiayaKonsultasiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputBiayaKonsultasiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputBiayaKonsultasiPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(inputBiayaKonsultasiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(inputBiayaKonsultasiLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        inputBiayaKonsultasiPanelLayout.setVerticalGroup(
            inputBiayaKonsultasiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputBiayaKonsultasiPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inputBiayaKonsultasiLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputBiayaKonsultasiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        inputKeluhanUtamaPanel.setBackground(new java.awt.Color(255, 255, 255));

        inputKeluhanUtamaLabel.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        inputKeluhanUtamaLabel.setText("Keluhan Utama");

        inputKeluhanUtamaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputKeluhanUtamaTextFieldActionPerformed(evt);
            }
        });
        inputKeluhanUtamaScrollPane.setViewportView(inputKeluhanUtamaTextField);

        javax.swing.GroupLayout inputKeluhanUtamaPanelLayout = new javax.swing.GroupLayout(inputKeluhanUtamaPanel);
        inputKeluhanUtamaPanel.setLayout(inputKeluhanUtamaPanelLayout);
        inputKeluhanUtamaPanelLayout.setHorizontalGroup(
            inputKeluhanUtamaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputKeluhanUtamaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputKeluhanUtamaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputKeluhanUtamaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputKeluhanUtamaLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        inputKeluhanUtamaPanelLayout.setVerticalGroup(
            inputKeluhanUtamaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputKeluhanUtamaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputKeluhanUtamaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputKeluhanUtamaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        simpanButton.setBackground(new java.awt.Color(51, 178, 73));
        simpanButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        simpanButton.setForeground(new java.awt.Color(255, 255, 255));
        simpanButton.setText("Simpan");
        simpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanButtonActionPerformed(evt);
            }
        });

        inputHasilPemeriksaanPanel.setBackground(new java.awt.Color(255, 255, 255));

        inputHasilPemeriksaanLabel.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        inputHasilPemeriksaanLabel.setText("Hasil Pemeriksaan");

        inputHasilPemeriksaanTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputHasilPemeriksaanTextFieldActionPerformed(evt);
            }
        });
        inputHasilPemeriksaanScrollPane.setViewportView(inputHasilPemeriksaanTextField);

        javax.swing.GroupLayout inputHasilPemeriksaanPanelLayout = new javax.swing.GroupLayout(inputHasilPemeriksaanPanel);
        inputHasilPemeriksaanPanel.setLayout(inputHasilPemeriksaanPanelLayout);
        inputHasilPemeriksaanPanelLayout.setHorizontalGroup(
            inputHasilPemeriksaanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputHasilPemeriksaanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputHasilPemeriksaanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputHasilPemeriksaanPanelLayout.createSequentialGroup()
                        .addComponent(inputHasilPemeriksaanLabel)
                        .addGap(0, 56, Short.MAX_VALUE))
                    .addComponent(inputHasilPemeriksaanScrollPane))
                .addContainerGap())
        );
        inputHasilPemeriksaanPanelLayout.setVerticalGroup(
            inputHasilPemeriksaanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputHasilPemeriksaanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputHasilPemeriksaanLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputHasilPemeriksaanScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout formInputDataKunjunganPanelLayout = new javax.swing.GroupLayout(formInputDataKunjunganPanel);
        formInputDataKunjunganPanel.setLayout(formInputDataKunjunganPanelLayout);
        formInputDataKunjunganPanelLayout.setHorizontalGroup(
            formInputDataKunjunganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formInputDataKunjunganPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formInputDataKunjunganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formInputDataKunjunganLabel)
                    .addComponent(inputIdKunjunganPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputTanggalKunjunganPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputIdDiagnosaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(formInputDataKunjunganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(formInputDataKunjunganPanelLayout.createSequentialGroup()
                        .addComponent(inputIdResepPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputBiayaKonsultasiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(formInputDataKunjunganPanelLayout.createSequentialGroup()
                        .addGroup(formInputDataKunjunganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inputNomorRekamMedisPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputJamKunjunganPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(formInputDataKunjunganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inputPilihDokterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputStatusKunjunganPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(formInputDataKunjunganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formInputDataKunjunganPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(simpanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(batalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formInputDataKunjunganPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputKeluhanUtamaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputHasilPemeriksaanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        formInputDataKunjunganPanelLayout.setVerticalGroup(
            formInputDataKunjunganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formInputDataKunjunganPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(formInputDataKunjunganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formInputDataKunjunganPanelLayout.createSequentialGroup()
                        .addComponent(formInputDataKunjunganLabel)
                        .addGroup(formInputDataKunjunganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formInputDataKunjunganPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(formInputDataKunjunganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(inputPilihDokterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(inputNomorRekamMedisPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(formInputDataKunjunganPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(inputIdKunjunganPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(formInputDataKunjunganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputTanggalKunjunganPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputJamKunjunganPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputStatusKunjunganPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(formInputDataKunjunganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputIdResepPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputIdDiagnosaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputBiayaKonsultasiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(formInputDataKunjunganPanelLayout.createSequentialGroup()
                        .addGroup(formInputDataKunjunganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputKeluhanUtamaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputHasilPemeriksaanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(formInputDataKunjunganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(simpanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(batalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        searchKunjunganPanel.setBackground(new java.awt.Color(255, 255, 255));

        judulKunjunganLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        judulKunjunganLabel.setText("Data Master Manajemen Kunjungan");

        subJudulKunjunganLabel.setText("Pencatatan data kunjungan pasien, diagnosa, dan administrasi konsultasi");

        searchKunjunganButton.setBackground(new java.awt.Color(0, 0, 153));
        searchKunjunganButton.setForeground(new java.awt.Color(255, 255, 255));
        searchKunjunganButton.setText("Cari");

        searchKunjunganLabel.setText("Pencarian Kunjungan");

        javax.swing.GroupLayout searchKunjunganPanelLayout = new javax.swing.GroupLayout(searchKunjunganPanel);
        searchKunjunganPanel.setLayout(searchKunjunganPanelLayout);
        searchKunjunganPanelLayout.setHorizontalGroup(
            searchKunjunganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchKunjunganPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchKunjunganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subJudulKunjunganLabel)
                    .addComponent(judulKunjunganLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(searchKunjunganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchKunjunganPanelLayout.createSequentialGroup()
                        .addComponent(searchKunjunganTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchKunjunganButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(searchKunjunganLabel))
                .addGap(20, 20, 20))
        );
        searchKunjunganPanelLayout.setVerticalGroup(
            searchKunjunganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchKunjunganPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(searchKunjunganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(judulKunjunganLabel)
                    .addComponent(searchKunjunganLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchKunjunganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchKunjunganButton)
                    .addComponent(subJudulKunjunganLabel)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchKunjunganPanelLayout.createSequentialGroup()
                        .addComponent(searchKunjunganTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        metricCardPanel.setBackground(new java.awt.Color(255, 255, 255));

        antrianCardPanel.setBackground(new java.awt.Color(0, 0, 153));
        antrianCardPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        antrianCardLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        antrianCardLabel.setForeground(new java.awt.Color(255, 255, 255));
        antrianCardLabel.setText("Antrian Aktif");

        antrianNumber.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        antrianNumber.setForeground(new java.awt.Color(255, 255, 255));
        antrianNumber.setText("0");

        javax.swing.GroupLayout antrianCardPanelLayout = new javax.swing.GroupLayout(antrianCardPanel);
        antrianCardPanel.setLayout(antrianCardPanelLayout);
        antrianCardPanelLayout.setHorizontalGroup(
            antrianCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(antrianCardPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(antrianCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(antrianCardLabel)
                    .addGroup(antrianCardPanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(antrianNumber)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        antrianCardPanelLayout.setVerticalGroup(
            antrianCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(antrianCardPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(antrianCardLabel)
                .addGap(18, 18, 18)
                .addComponent(antrianNumber)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kunjunganSelesaiCardPanel.setBackground(new java.awt.Color(153, 153, 255));
        kunjunganSelesaiCardPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        kunjunganSelesaiCardLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        kunjunganSelesaiCardLabel.setForeground(new java.awt.Color(255, 255, 255));
        kunjunganSelesaiCardLabel.setText("Kunjungan Selesai");

        kunjunganAntrianNumber.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        kunjunganAntrianNumber.setForeground(new java.awt.Color(255, 255, 255));
        kunjunganAntrianNumber.setText("0");

        javax.swing.GroupLayout kunjunganSelesaiCardPanelLayout = new javax.swing.GroupLayout(kunjunganSelesaiCardPanel);
        kunjunganSelesaiCardPanel.setLayout(kunjunganSelesaiCardPanelLayout);
        kunjunganSelesaiCardPanelLayout.setHorizontalGroup(
            kunjunganSelesaiCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kunjunganSelesaiCardPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(kunjunganSelesaiCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kunjunganSelesaiCardLabel)
                    .addGroup(kunjunganSelesaiCardPanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(kunjunganAntrianNumber)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        kunjunganSelesaiCardPanelLayout.setVerticalGroup(
            kunjunganSelesaiCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kunjunganSelesaiCardPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(kunjunganSelesaiCardLabel)
                .addGap(18, 18, 18)
                .addComponent(kunjunganAntrianNumber)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        totalPendapatanCardPanel.setBackground(new java.awt.Color(0, 0, 153));
        totalPendapatanCardPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        totalPendapatanCardLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        totalPendapatanCardLabel.setForeground(new java.awt.Color(255, 255, 255));
        totalPendapatanCardLabel.setText("Total Pendapatan");

        totalPendapatanNumber.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        totalPendapatanNumber.setForeground(new java.awt.Color(255, 255, 255));
        totalPendapatanNumber.setText("Rp0");

        javax.swing.GroupLayout totalPendapatanCardPanelLayout = new javax.swing.GroupLayout(totalPendapatanCardPanel);
        totalPendapatanCardPanel.setLayout(totalPendapatanCardPanelLayout);
        totalPendapatanCardPanelLayout.setHorizontalGroup(
            totalPendapatanCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalPendapatanCardPanelLayout.createSequentialGroup()
                .addGroup(totalPendapatanCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(totalPendapatanCardPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(totalPendapatanCardLabel))
                    .addGroup(totalPendapatanCardPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(totalPendapatanNumber)))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        totalPendapatanCardPanelLayout.setVerticalGroup(
            totalPendapatanCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalPendapatanCardPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(totalPendapatanCardLabel)
                .addGap(18, 18, 18)
                .addComponent(totalPendapatanNumber)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout metricCardPanelLayout = new javax.swing.GroupLayout(metricCardPanel);
        metricCardPanel.setLayout(metricCardPanelLayout);
        metricCardPanelLayout.setHorizontalGroup(
            metricCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(metricCardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(antrianCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kunjunganSelesaiCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(totalPendapatanCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        metricCardPanelLayout.setVerticalGroup(
            metricCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(metricCardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(metricCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kunjunganSelesaiCardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(antrianCardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalPendapatanCardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        kunjunganTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        kunjunganScrollPane.setViewportView(kunjunganTable);

        kunjunganButtonPanel.setBackground(new java.awt.Color(255, 255, 255));

        tanbahKunjunganButton.setBackground(new java.awt.Color(51, 178, 73));
        tanbahKunjunganButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        tanbahKunjunganButton.setForeground(new java.awt.Color(255, 255, 255));
        tanbahKunjunganButton.setText("Tambah");
        tanbahKunjunganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanbahKunjunganButtonActionPerformed(evt);
            }
        });

        barukanKunjunganButton.setBackground(new java.awt.Color(255, 204, 51));
        barukanKunjunganButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        barukanKunjunganButton.setForeground(new java.awt.Color(255, 255, 255));
        barukanKunjunganButton.setText("Barukan");
        barukanKunjunganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barukanKunjunganButtonActionPerformed(evt);
            }
        });

        hapusKunjunganButton.setBackground(new java.awt.Color(255, 0, 0));
        hapusKunjunganButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        hapusKunjunganButton.setForeground(new java.awt.Color(255, 255, 255));
        hapusKunjunganButton.setText("Hapus");
        hapusKunjunganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusKunjunganButtonActionPerformed(evt);
            }
        });

        kunjunganButtonLabel.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        kunjunganButtonLabel.setText("Aksi");

        javax.swing.GroupLayout kunjunganButtonPanelLayout = new javax.swing.GroupLayout(kunjunganButtonPanel);
        kunjunganButtonPanel.setLayout(kunjunganButtonPanelLayout);
        kunjunganButtonPanelLayout.setHorizontalGroup(
            kunjunganButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kunjunganButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kunjunganButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kunjunganButtonLabel)
                    .addComponent(tanbahKunjunganButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(barukanKunjunganButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hapusKunjunganButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        kunjunganButtonPanelLayout.setVerticalGroup(
            kunjunganButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kunjunganButtonPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(kunjunganButtonLabel)
                .addGap(18, 18, 18)
                .addGroup(kunjunganButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tanbahKunjunganButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barukanKunjunganButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hapusKunjunganButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(formInputDataKunjunganPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchKunjunganPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(metricCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kunjunganButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(kunjunganScrollPane))
                .addContainerGap(311, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(searchKunjunganPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kunjunganButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(metricCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formInputDataKunjunganPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kunjunganScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inputNomorRekamMedisTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNomorRekamMedisTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNomorRekamMedisTextFieldActionPerformed

    private void inputJamKunjunganTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputJamKunjunganTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputJamKunjunganTextFieldActionPerformed

    private void inputIdResepTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIdResepTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputIdResepTextFieldActionPerformed

    private void inputBiayaKonsultasiTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBiayaKonsultasiTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputBiayaKonsultasiTextFieldActionPerformed

    private void inputKeluhanUtamaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputKeluhanUtamaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputKeluhanUtamaTextFieldActionPerformed

    private void inputHasilPemeriksaanTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputHasilPemeriksaanTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputHasilPemeriksaanTextFieldActionPerformed

    private void simpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_simpanButtonActionPerformed

    private void tanbahKunjunganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanbahKunjunganButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanbahKunjunganButtonActionPerformed

    private void barukanKunjunganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barukanKunjunganButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barukanKunjunganButtonActionPerformed

    private void hapusKunjunganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusKunjunganButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hapusKunjunganButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel antrianCardLabel;
    private javax.swing.JPanel antrianCardPanel;
    private javax.swing.JLabel antrianNumber;
    private javax.swing.JButton barukanKunjunganButton;
    private javax.swing.JButton batalButton;
    private javax.swing.JLabel formInputDataKunjunganLabel;
    private javax.swing.JPanel formInputDataKunjunganPanel;
    private javax.swing.JButton hapusKunjunganButton;
    private javax.swing.JLabel inputBiayaKonsultasiLabel;
    private javax.swing.JPanel inputBiayaKonsultasiPanel;
    private javax.swing.JTextField inputBiayaKonsultasiTextField;
    private javax.swing.JLabel inputHasilPemeriksaanLabel;
    private javax.swing.JPanel inputHasilPemeriksaanPanel;
    private javax.swing.JScrollPane inputHasilPemeriksaanScrollPane;
    private javax.swing.JTextField inputHasilPemeriksaanTextField;
    private javax.swing.JLabel inputIdDiagnosaLabel;
    private javax.swing.JPanel inputIdDiagnosaPanel;
    private javax.swing.JTextField inputIdDiagnosaTextField;
    private javax.swing.JLabel inputIdKunjunganLabel;
    private javax.swing.JPanel inputIdKunjunganPanel;
    private javax.swing.JTextField inputIdKunjunganTextField;
    private javax.swing.JLabel inputIdResepLabel;
    private javax.swing.JPanel inputIdResepPanel;
    private javax.swing.JTextField inputIdResepTextField;
    private javax.swing.JLabel inputJamKunjunganLabel;
    private javax.swing.JPanel inputJamKunjunganPanel;
    private javax.swing.JTextField inputJamKunjunganTextField;
    private javax.swing.JLabel inputKeluhanUtamaLabel;
    private javax.swing.JPanel inputKeluhanUtamaPanel;
    private javax.swing.JScrollPane inputKeluhanUtamaScrollPane;
    private javax.swing.JTextField inputKeluhanUtamaTextField;
    private javax.swing.JLabel inputNomorRekamMedisLabel;
    private javax.swing.JPanel inputNomorRekamMedisPanel;
    private javax.swing.JTextField inputNomorRekamMedisTextField;
    private javax.swing.JComboBox<String> inputPilihDokterComboBox;
    private javax.swing.JLabel inputPilihDokterLabel;
    private javax.swing.JPanel inputPilihDokterPanel;
    private javax.swing.JComboBox<String> inputStatusKunjunganComboBox;
    private javax.swing.JLabel inputStatusKunjunganLabel;
    private javax.swing.JPanel inputStatusKunjunganPanel;
    private com.toedter.calendar.JDateChooser inputTanggalKunjunganDateChooser;
    private javax.swing.JLabel inputTanggalKunjunganLabel;
    private javax.swing.JPanel inputTanggalKunjunganPanel;
    private javax.swing.JLabel judulKunjunganLabel;
    private javax.swing.JLabel kunjunganAntrianNumber;
    private javax.swing.JLabel kunjunganButtonLabel;
    private javax.swing.JPanel kunjunganButtonPanel;
    private javax.swing.JScrollPane kunjunganScrollPane;
    private javax.swing.JLabel kunjunganSelesaiCardLabel;
    private javax.swing.JPanel kunjunganSelesaiCardPanel;
    private javax.swing.JTable kunjunganTable;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel metricCardPanel;
    private javax.swing.JButton searchKunjunganButton;
    private javax.swing.JLabel searchKunjunganLabel;
    private javax.swing.JPanel searchKunjunganPanel;
    private javax.swing.JTextField searchKunjunganTextField;
    private javax.swing.JButton simpanButton;
    private javax.swing.JLabel subJudulKunjunganLabel;
    private javax.swing.JButton tanbahKunjunganButton;
    private javax.swing.JLabel totalPendapatanCardLabel;
    private javax.swing.JPanel totalPendapatanCardPanel;
    private javax.swing.JLabel totalPendapatanNumber;
    // End of variables declaration//GEN-END:variables
}
