/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

public class LoginPanel extends javax.swing.JPanel {
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        NavbarPanel = new javax.swing.JPanel();
        NavbarLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        FormInputPanel = new javax.swing.JPanel();
        FormInputLabel1 = new javax.swing.JLabel();
        FormInputLabel2 = new javax.swing.JLabel();
        InputPanel = new javax.swing.JPanel();
        InputUsernamePanel = new javax.swing.JPanel();
        inputUsernameLabel = new javax.swing.JLabel();
        inputUsernameTextField = new javax.swing.JTextField();
        inputPasswordPanel = new javax.swing.JPanel();
        inputPasswordLabel = new javax.swing.JLabel();
        inputPasswordTextField = new javax.swing.JTextField();
        inputLoginPassword = new javax.swing.JButton();
        imageFormInput = new javax.swing.JLabel();

        mainPanel.setBackground(new java.awt.Color(250, 250, 253));

        NavbarPanel.setBackground(new java.awt.Color(255, 255, 255));

        NavbarLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        NavbarLabel.setText("Klinik Atma Sehat");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Logo_Tubes (1)_1.png"))); // NOI18N

        javax.swing.GroupLayout NavbarPanelLayout = new javax.swing.GroupLayout(NavbarPanel);
        NavbarPanel.setLayout(NavbarPanelLayout);
        NavbarPanelLayout.setHorizontalGroup(
            NavbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavbarPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NavbarLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NavbarPanelLayout.setVerticalGroup(
            NavbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavbarPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(NavbarLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NavbarPanelLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        FormInputPanel.setBackground(new java.awt.Color(255, 255, 255));

        FormInputLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        FormInputLabel1.setText(" MASUK");

        FormInputLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        FormInputLabel2.setText("Silakan masukkan kredensial Anda untuk mengakses rekam medis Anda.");

        InputPanel.setBackground(new java.awt.Color(255, 255, 255));

        InputUsernamePanel.setBackground(new java.awt.Color(255, 255, 255));
        InputUsernamePanel.setPreferredSize(new java.awt.Dimension(555, 87));

        inputUsernameLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        inputUsernameLabel.setText("Username");

        inputUsernameTextField.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        javax.swing.GroupLayout InputUsernamePanelLayout = new javax.swing.GroupLayout(InputUsernamePanel);
        InputUsernamePanel.setLayout(InputUsernamePanelLayout);
        InputUsernamePanelLayout.setHorizontalGroup(
            InputUsernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputUsernamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InputUsernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InputUsernamePanelLayout.createSequentialGroup()
                        .addComponent(inputUsernameLabel)
                        .addGap(0, 475, Short.MAX_VALUE))
                    .addComponent(inputUsernameTextField))
                .addContainerGap())
        );
        InputUsernamePanelLayout.setVerticalGroup(
            InputUsernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputUsernamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputUsernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(inputUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        inputPasswordPanel.setBackground(new java.awt.Color(255, 255, 255));

        inputPasswordLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        inputPasswordLabel.setText("Password");

        inputPasswordTextField.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        javax.swing.GroupLayout inputPasswordPanelLayout = new javax.swing.GroupLayout(inputPasswordPanel);
        inputPasswordPanel.setLayout(inputPasswordPanelLayout);
        inputPasswordPanelLayout.setHorizontalGroup(
            inputPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPasswordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputPasswordPanelLayout.createSequentialGroup()
                        .addComponent(inputPasswordLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(inputPasswordTextField))
                .addContainerGap())
        );
        inputPasswordPanelLayout.setVerticalGroup(
            inputPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPasswordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputPasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(inputPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        inputLoginPassword.setBackground(new java.awt.Color(91, 101, 220));
        inputLoginPassword.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        inputLoginPassword.setForeground(new java.awt.Color(255, 255, 255));
        inputLoginPassword.setText("Masuk");

        imageFormInput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Img Login.jpg"))); // NOI18N

        javax.swing.GroupLayout InputPanelLayout = new javax.swing.GroupLayout(InputPanel);
        InputPanel.setLayout(InputPanelLayout);
        InputPanelLayout.setHorizontalGroup(
            InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputLoginPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputPasswordPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imageFormInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 579, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InputPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(InputUsernamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        InputPanelLayout.setVerticalGroup(
            InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageFormInput, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(inputPasswordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(inputLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(InputPanelLayout.createSequentialGroup()
                    .addGap(175, 175, 175)
                    .addComponent(InputUsernamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(181, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout FormInputPanelLayout = new javax.swing.GroupLayout(FormInputPanel);
        FormInputPanel.setLayout(FormInputPanelLayout);
        FormInputPanelLayout.setHorizontalGroup(
            FormInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormInputPanelLayout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(InputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(FormInputPanelLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(FormInputLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(FormInputPanelLayout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(FormInputLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FormInputPanelLayout.setVerticalGroup(
            FormInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormInputPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(FormInputLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FormInputLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NavbarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(369, Short.MAX_VALUE)
                .addComponent(FormInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(327, 327, 327))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NavbarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(FormInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FormInputLabel1;
    private javax.swing.JLabel FormInputLabel2;
    private javax.swing.JPanel FormInputPanel;
    private javax.swing.JPanel InputPanel;
    private javax.swing.JPanel InputUsernamePanel;
    private javax.swing.JLabel NavbarLabel;
    private javax.swing.JPanel NavbarPanel;
    private javax.swing.JLabel imageFormInput;
    private javax.swing.JButton inputLoginPassword;
    private javax.swing.JLabel inputPasswordLabel;
    private javax.swing.JPanel inputPasswordPanel;
    private javax.swing.JTextField inputPasswordTextField;
    private javax.swing.JLabel inputUsernameLabel;
    private javax.swing.JTextField inputUsernameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
