/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import util.DialogUtil;

import control.AdminControl;
import control.DokterControl;
import exception.DataTidakDitemukanException;
import exception.InputKosongException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Admin;
import model.Dokter;

/**
 *
 * @author Divo Pratama
 */
public class LoginForm extends JFrame {

    public LoginForm() {
        initComponents();
        inputPasswordPasswordField.setEchoChar('*');
        setLocationRelativeTo(null);
    }

    private void handleLogin() {
        String username = inputUsernameTextField.getText().trim();
        String password = new String(inputPasswordPasswordField.getPassword()).trim();
//        username = "hendra.dokter";
//        password = "dokter123";

        AdminControl adminControl = new AdminControl();
        try {
            Admin admin = adminControl.masuk(username, password);
            new MainViewFormAdmin().setVisible(true);
            this.dispose();
            return;
        } catch (InputKosongException e) {
            DialogUtil.showMessageDialog(this, "Username dan password tidak boleh kosong!",
                    "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        } catch (DataTidakDitemukanException e) {}

        DokterControl dokterControl = new DokterControl();
        try {
            Dokter dokter = dokterControl.masuk(username, password);
            new MainViewFormDokter(dokter.getId()).setVisible(true);
            this.dispose();
        } catch (InputKosongException e) {
            DialogUtil.showMessageDialog(this, "Username dan password tidak boleh kosong!",
                    "Peringatan", JOptionPane.WARNING_MESSAGE);
        } catch (DataTidakDitemukanException e) {
            DialogUtil.showMessageDialog(this, "Username atau password salah!",
                    "Login Gagal", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        NavbarPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        FormInputPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        FormInputLabel1 = new javax.swing.JLabel();
        FormInputLabel2 = new javax.swing.JLabel();
        logoLabel2 = new javax.swing.JLabel();
        InputPanel = new javax.swing.JPanel();
        InputUsernamePanel = new javax.swing.JPanel();
        inputUsernameLabel = new javax.swing.JLabel();
        inputUsernameTextField = new javax.swing.JTextField();
        inputPasswordPanel = new javax.swing.JPanel();
        inputPasswordLabel = new javax.swing.JLabel();
        inputPasswordPasswordField = new javax.swing.JPasswordField();
        inputLoginPassword = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(250, 250, 253));
        mainPanel.setPreferredSize(new java.awt.Dimension(900, 560));

        NavbarPanel.setBackground(new java.awt.Color(255, 255, 255));
        NavbarPanel.setPreferredSize(new java.awt.Dimension(450, 560));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LoginGrafisV2.png"))); // NOI18N

        javax.swing.GroupLayout NavbarPanelLayout = new javax.swing.GroupLayout(NavbarPanel);
        NavbarPanel.setLayout(NavbarPanelLayout);
        NavbarPanelLayout.setHorizontalGroup(
            NavbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 313, Short.MAX_VALUE)
        );
        NavbarPanelLayout.setVerticalGroup(
            NavbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NavbarPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        FormInputPanel.setBackground(new java.awt.Color(255, 255, 255));
        FormInputPanel.setPreferredSize(new java.awt.Dimension(450, 560));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Logo_Tubes (1)_1.png"))); // NOI18N

        FormInputLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 35)); // NOI18N
        FormInputLabel1.setText("Selamat datang kembali!");

        FormInputLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        FormInputLabel2.setText("Silakan masukkan kredensial Anda untuk mengakses rekam medis Anda.");

        logoLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 22)); // NOI18N
        logoLabel2.setForeground(new java.awt.Color(51, 0, 153));
        logoLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel2.setText("Klinik Atma Sehat");

        InputPanel.setBackground(new java.awt.Color(255, 255, 255));

        InputUsernamePanel.setBackground(new java.awt.Color(255, 255, 255));
        InputUsernamePanel.setPreferredSize(new java.awt.Dimension(555, 87));

        inputUsernameLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        inputUsernameLabel.setText("Username");

        inputUsernameTextField.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        inputUsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputUsernameTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InputUsernamePanelLayout = new javax.swing.GroupLayout(InputUsernamePanel);
        InputUsernamePanel.setLayout(InputUsernamePanelLayout);
        InputUsernamePanelLayout.setHorizontalGroup(
            InputUsernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inputUsernameTextField, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(InputUsernamePanelLayout.createSequentialGroup()
                .addComponent(inputUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 336, Short.MAX_VALUE))
        );
        InputUsernamePanelLayout.setVerticalGroup(
            InputUsernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputUsernamePanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(inputUsernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        inputPasswordPanel.setBackground(new java.awt.Color(255, 255, 255));

        inputPasswordLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        inputPasswordLabel.setText("Password");

        inputPasswordPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPasswordPasswordFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputPasswordPanelLayout = new javax.swing.GroupLayout(inputPasswordPanel);
        inputPasswordPanel.setLayout(inputPasswordPanelLayout);
        inputPasswordPanelLayout.setHorizontalGroup(
            inputPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPasswordPanelLayout.createSequentialGroup()
                .addComponent(inputPasswordLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(inputPasswordPasswordField)
        );
        inputPasswordPanelLayout.setVerticalGroup(
            inputPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPasswordPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(inputPasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPasswordPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        inputLoginPassword.setBackground(new java.awt.Color(91, 101, 220));
        inputLoginPassword.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        inputLoginPassword.setForeground(new java.awt.Color(255, 255, 255));
        inputLoginPassword.setText("Masuk");
        inputLoginPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputLoginPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InputPanelLayout = new javax.swing.GroupLayout(InputPanel);
        InputPanel.setLayout(InputPanelLayout);
        InputPanelLayout.setHorizontalGroup(
            InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputPanelLayout.createSequentialGroup()
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(inputLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, InputPanelLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(InputUsernamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                            .addComponent(inputPasswordPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        InputPanelLayout.setVerticalGroup(
            InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InputUsernamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPasswordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inputLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout FormInputPanelLayout = new javax.swing.GroupLayout(FormInputPanel);
        FormInputPanel.setLayout(FormInputPanelLayout);
        FormInputPanelLayout.setHorizontalGroup(
            FormInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormInputPanelLayout.createSequentialGroup()
                .addGap(0, 23, Short.MAX_VALUE)
                .addComponent(InputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormInputPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(FormInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormInputPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(FormInputLabel2))
                    .addComponent(FormInputLabel1))
                .addGap(69, 69, 69))
            .addGroup(FormInputPanelLayout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(logoLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(FormInputPanelLayout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FormInputPanelLayout.setVerticalGroup(
            FormInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormInputPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoLabel2)
                .addGap(38, 38, 38)
                .addComponent(FormInputLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FormInputLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(NavbarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(FormInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(FormInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(NavbarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputLoginPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputLoginPasswordActionPerformed
        handleLogin();
    }//GEN-LAST:event_inputLoginPasswordActionPerformed

    private void inputUsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputUsernameTextFieldActionPerformed
        handleLogin();
    }//GEN-LAST:event_inputUsernameTextFieldActionPerformed

    private void inputPasswordPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPasswordPasswordFieldActionPerformed
        handleLogin();
    }//GEN-LAST:event_inputPasswordPasswordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FormInputLabel1;
    private javax.swing.JLabel FormInputLabel2;
    private javax.swing.JPanel FormInputPanel;
    private javax.swing.JPanel InputPanel;
    private javax.swing.JPanel InputUsernamePanel;
    private javax.swing.JPanel NavbarPanel;
    private javax.swing.JButton inputLoginPassword;
    private javax.swing.JLabel inputPasswordLabel;
    private javax.swing.JPanel inputPasswordPanel;
    private javax.swing.JPasswordField inputPasswordPasswordField;
    private javax.swing.JLabel inputUsernameLabel;
    private javax.swing.JTextField inputUsernameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel logoLabel2;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
