/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.AdminControl;
import control.DokterControl;
import exception.DataTidakDitemukanException;
import exception.InputKosongException;
import javax.swing.UIManager;
import model.Admin;
import model.Dokter;

/**
 *
 * @author Divo Pratama
 */
public class LoginForm extends javax.swing.JFrame {

    private final StringBuilder passwordBuffer = new StringBuilder();

    public LoginForm() {
        initComponents();
        inputLoginPassword.addActionListener(e -> handleLogin());
        inputPasswordTextField.addActionListener(e -> handleLogin());
        inputUsernameTextField.addActionListener(e -> handleLogin());

        ((javax.swing.text.AbstractDocument) inputPasswordTextField.getDocument())
            .setDocumentFilter(new javax.swing.text.DocumentFilter() {
                @Override
                public void insertString(FilterBypass fb, int offset, String string,
                        javax.swing.text.AttributeSet attr) throws javax.swing.text.BadLocationException {
                    if (string == null) return;
                    passwordBuffer.insert(offset, string);
                    super.insertString(fb, offset, mask(string.length()), attr);
                }
                @Override
                public void replace(FilterBypass fb, int offset, int length, String string,
                        javax.swing.text.AttributeSet attr) throws javax.swing.text.BadLocationException {
                    if (length > 0) passwordBuffer.delete(offset, offset + length);
                    if (string != null) passwordBuffer.insert(offset, string);
                    super.replace(fb, offset, length, string != null ? mask(string.length()) : "", attr);
                }
                @Override
                public void remove(FilterBypass fb, int offset, int length)
                        throws javax.swing.text.BadLocationException {
                    passwordBuffer.delete(offset, offset + length);
                    super.remove(fb, offset, length);
                }
                private String mask(int length) {
                    StringBuilder sb = new StringBuilder();
                    for (int i = 0; i < length; i++) sb.append('*');
                    return sb.toString();
                }
            });

        setLocationRelativeTo(null);
    }

    private void handleLogin() {
        String username = inputUsernameTextField.getText().trim();
        String password = passwordBuffer.toString().trim();
        username = "andi.dokter";
        password = "dokter123";

        AdminControl adminControl = new AdminControl();
        try {
            Admin admin = adminControl.masuk(username, password);
            new MainViewFormAdmin().setVisible(true);
            this.dispose();
            return;
        } catch (InputKosongException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Username dan password tidak boleh kosong!",
                    "Peringatan",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        } catch (DataTidakDitemukanException e) {
            // bukan admin, coba sebagai dokter
        }

        DokterControl dokterControl = new DokterControl();
        try {
            Dokter dokter = dokterControl.masuk(username, password);
            new MainViewFormDokter(dokter.getId()).setVisible(true);
            this.dispose();
        } catch (InputKosongException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Username dan password tidak boleh kosong!",
                    "Peringatan",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
        } catch (DataTidakDitemukanException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Username atau password salah!",
                    "Login Gagal",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        NavbarPanel = new javax.swing.JPanel();
        NavbarLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        FormInputPanel = new javax.swing.JPanel();
        FormInputLabel1 = new javax.swing.JLabel();
        FormInputLabel2 = new javax.swing.JLabel();
        InputPanel = new javax.swing.JPanel();
        InputUsernamePanel = new javax.swing.JPanel();
        inputUsernameLabel = new javax.swing.JLabel();
        inputUsernameTextField = new javax.swing.JTextField();
        inputPasswordPanel = new javax.swing.JPanel();
        inputPasswordLabel = new javax.swing.JLabel();
        inputPasswordTextField = new javax.swing.JTextField();
        inputLoginPassword = new javax.swing.JButton();
        imageFormInput = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(250, 250, 253));

        NavbarPanel.setBackground(new java.awt.Color(255, 255, 255));

        NavbarLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        NavbarLabel.setText("Klinik Atma Sehat");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Logo_Tubes (1)_1.png"))); // NOI18N

        javax.swing.GroupLayout NavbarPanelLayout = new javax.swing.GroupLayout(NavbarPanel);
        NavbarPanel.setLayout(NavbarPanelLayout);
        NavbarPanelLayout.setHorizontalGroup(
            NavbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavbarPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NavbarLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NavbarPanelLayout.setVerticalGroup(
            NavbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavbarPanelLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(NavbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NavbarPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NavbarPanelLayout.createSequentialGroup()
                        .addComponent(NavbarLabel)
                        .addGap(26, 26, 26))))
        );

        FormInputPanel.setBackground(new java.awt.Color(255, 255, 255));

        FormInputLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        FormInputLabel1.setText(" MASUK");

        FormInputLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        FormInputLabel2.setText("Silakan masukkan kredensial Anda untuk mengakses rekam medis Anda.");

        InputPanel.setBackground(new java.awt.Color(255, 255, 255));

        InputUsernamePanel.setBackground(new java.awt.Color(255, 255, 255));
        InputUsernamePanel.setPreferredSize(new java.awt.Dimension(555, 87));

        inputUsernameLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        inputUsernameLabel.setText("Username");

        inputUsernameTextField.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        javax.swing.GroupLayout InputUsernamePanelLayout = new javax.swing.GroupLayout(InputUsernamePanel);
        InputUsernamePanel.setLayout(InputUsernamePanelLayout);
        InputUsernamePanelLayout.setHorizontalGroup(
            InputUsernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputUsernamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InputUsernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputUsernameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                    .addGroup(InputUsernamePanelLayout.createSequentialGroup()
                        .addComponent(inputUsernameLabel)
                        .addGap(0, 475, Short.MAX_VALUE)))
                .addContainerGap())
        );
        InputUsernamePanelLayout.setVerticalGroup(
            InputUsernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputUsernamePanelLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(inputUsernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        inputPasswordPanel.setBackground(new java.awt.Color(255, 255, 255));

        inputPasswordLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        inputPasswordLabel.setText("Password");

        inputPasswordTextField.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        inputPasswordTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputPasswordTextFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout inputPasswordPanelLayout = new javax.swing.GroupLayout(inputPasswordPanel);
        inputPasswordPanel.setLayout(inputPasswordPanelLayout);
        inputPasswordPanelLayout.setHorizontalGroup(
            inputPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPasswordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputPasswordTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                    .addGroup(inputPasswordPanelLayout.createSequentialGroup()
                        .addComponent(inputPasswordLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        inputPasswordPanelLayout.setVerticalGroup(
            inputPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPasswordPanelLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(inputPasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        inputLoginPassword.setBackground(new java.awt.Color(91, 101, 220));
        inputLoginPassword.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        inputLoginPassword.setForeground(new java.awt.Color(255, 255, 255));
        inputLoginPassword.setText("Masuk");
        inputLoginPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputLoginPasswordActionPerformed(evt);
            }
        });

        imageFormInput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Img Login.jpg"))); // NOI18N

        javax.swing.GroupLayout InputPanelLayout = new javax.swing.GroupLayout(InputPanel);
        InputPanel.setLayout(InputPanelLayout);
        InputPanelLayout.setHorizontalGroup(
            InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputLoginPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputPasswordPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imageFormInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 579, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InputPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(InputUsernamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        InputPanelLayout.setVerticalGroup(
            InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageFormInput, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(inputPasswordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(inputLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(InputPanelLayout.createSequentialGroup()
                    .addGap(175, 175, 175)
                    .addComponent(InputUsernamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(181, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout FormInputPanelLayout = new javax.swing.GroupLayout(FormInputPanel);
        FormInputPanel.setLayout(FormInputPanelLayout);
        FormInputPanelLayout.setHorizontalGroup(
            FormInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormInputPanelLayout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(InputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(FormInputPanelLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(FormInputLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(FormInputPanelLayout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(FormInputLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FormInputPanelLayout.setVerticalGroup(
            FormInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormInputPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(FormInputLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FormInputLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NavbarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(FormInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NavbarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FormInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputLoginPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputLoginPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputLoginPasswordActionPerformed

    private void inputPasswordTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputPasswordTextFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPasswordTextFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FormInputLabel1;
    private javax.swing.JLabel FormInputLabel2;
    private javax.swing.JPanel FormInputPanel;
    private javax.swing.JPanel InputPanel;
    private javax.swing.JPanel InputUsernamePanel;
    private javax.swing.JLabel NavbarLabel;
    private javax.swing.JPanel NavbarPanel;
    private javax.swing.JLabel imageFormInput;
    private javax.swing.JButton inputLoginPassword;
    private javax.swing.JLabel inputPasswordLabel;
    private javax.swing.JPanel inputPasswordPanel;
    private javax.swing.JTextField inputPasswordTextField;
    private javax.swing.JLabel inputUsernameLabel;
    private javax.swing.JTextField inputUsernameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
